'''
Descriptors: the adjective of a title, the X of "The X Lord".

A vocabulary of Map_of_Titles: a word list keyed by what the lusor's genus
answers. The story engine (Map_of_Stories) may import it directly, without
the title composer.
'''

def Descriptor(
		lusor,
		*,
		dice=None,
		):
	'''
General Rule:
If you can say
- The X Lord -
And sounds cool
X goes here
'''
	try:
		genus = lusor.genus
	except:
		genus = lusor

	descriptor = []

	try:

		descriptor += [
			"Aquatic",
			"Adventurous",
			"Apprentice",
			"Ascended",
			"Ancient",
			"Accursed",
			"Abyssal",
			"Astral",
			"Ancient",
			"Accursed",
			"Amethyst",
			"Atmospheric",
			"Astronomical",
			"Aquatic",
			"Amulet",
			"Art",
			"Artistic",
			"Astral",
			"Alien",
			"Alpha",
			"Autumn",
			"Animal",
			"Atmospheric",
			"Archaic",
			"Antique",
			"Ancient",
			"Amulet",
			"Aurora",
			"Alchemic",
			"Amethyst",
			"Alabaster",
			"Alien",
			"Azure",
			"Amulet",
			"Arboreal",
			"Atmospheric",
			"Airy",
			"Aerial",
			"Astute",
			"Analytical",
			"Artistic",
			"Antagonistic",
			"Aggressive",
			"Acrimonious",
			"Abominable",
			"Ardent",
			"Angelic",
			"Amulet",
			"Antagonistic",
			"Acrimonious",
			"Abhorrent",
			"Ardent",
			"Amorous",
			"Affection",
			"Adoring",
			"Aristocratic",
			"Astronomical",
			"Antique",
			"Antediluvian",
			"Ancient",
			"Ancestral",
			"Ageless",
			"Astral",
			"Artifact",
			"Amulet",
			"Archaic",
			"Affectionate",
			"Aristocratic",
			"Archaic",
			"Antique",
			"Apostolic",
			"Astral",
			"Antediluvian",
			"Ancient",
			"Ancestral",
			"Atemporal",
			"Ancient",
			"Ancestral",
			"Anachronistic",
			"Ageless",
			"Ancient",
			"Amulet",
			"Abhorrent",
			"Abyssal",
			"Angelic",
			"Ageless",
			"Antediluvian",
			"Archipelago",
			"Alluring",
			"Archipelago",
			"Adorned",
			"Arctic",
			"Artistic",
			"Ascetic",
			"Ardent",
			"Arena",
			"Aristocratic",
			"Arrogant",
			"Artifact",
			"Asgardian",
			"Astral",
			"Astute",
			"Atlantean",
			"Aurora",
			"Autumn",
			"Awakened",
			"Aztec",
			"Azure",
			"Abominable",
			"Amazonian",
			"Amethyst",
			"Amulet",
			"Ardent",
			"Ancestral",
			"Ancient",
			"Antique",
			"Apostolic",
			"Aquatic",
			"Arachnid",
			"Arboreal",
			"Arcanic",
			"Arch",
			"Archaic",
			"Abyssal",
			"Aerial",
			"Ageless",
			"Alabaster",
			"Alchemical",
			"Alcoholic",
			"Alpha",
			"Amber",
			"Amber",
			"Augury",
			"Amber",
			"Ancient",
			"Ancient",
			"Ancient",
			"Ancient",
			"Ancient",
			"Aberrant",
			"Ancient",
			"Amber",
			"Ancient",
			"Apex",
			"Age-old",
			"Alpha",
			"Air",
			"Air",
			"All-Seeing",
			"Air",
			"Armored",
			"Aura",
			"Aura",
			"Alcoholic",
			"Astral",
			"Astral",
			"Archfey",
			"Awakened",
			"Autumn",
			"Antique",
			"Ageless",
			"Armored",
			"Armored",
			"Armorless",
			"All Seeing",
			"Awesome",
			]
		descriptor += [
			"Band",
			"Bloodmoon",
			"Blending",
			"Bat",
			"Black",
			"Blind",
			"Bursting",
			"Bone",
			"Bronze",
			"Book",
			"Burning",
			"Blizzard",
			"Book",
			"Brass",
			"Bronze",
			"Binding",
			"Boreal",
			"Bloodmoon",
			"Blizzard",
			"Black Hole",
			"Baroque",
			"Blade",
			"Battle",
			"Blight",
			"Bone",
			"Black",
			"Babylonian",
			"Badland",
			"Baleful",
			"Blade",
			"Black",
			"Baronial",
			"Baroque",
			"Barracks",
			"Barren",
			"Bat",
			"Battle",
			"Bark",
			"Battleground",
			"Bay",
			"Beach",
			"Behemoth",
			"Benevolent",
			"Beryl",
			"Bewitched",
			"Biblical",
			"Bitter",
			"Bramble",
			"Brass",
			"Brave",
			"Breezy",
			"Bridge",
			"Brimstone",
			"Bronze",
			"Bronze",
			"Brooch",
			"Burgundy",
			"Black",
			"Bog",
			"Bone",
			"Book",
			"Boreal",
			"Brain",
			"Blazing",
			"Burned",
			"Burning",
			"Bursting",
			"Butterfly",
			"Bygone",
			"Byzantine",
			"Blind",
			"Blizzard",
			"Blood",
			"Blooming",
			"Blossoming",
			"Blue",
			"Battle",
			"Basalt",
			"Broken",
			"Blood",
			"Battle",
			"Battle",
			"Battle",
			"Battle",
			"Brave",
			"Brave",
			"Bow",
			"Bold",
			"Bloodthirst",
			"Boreal",
			"Boreal",
			"Blue",
			"Blue",
			"Black",
			"Black",
			"Blood",
			"Blood",
			"Blood",
			"Blooming",
			"Brass",
			"Bursting",
			"Brain",
			"Butterfly",
			"Burning",
			"Blade",
			"Boundless",
			"Boundless",
			"Brimstone",
			"Burning",
			"Blood",
			"Beautiful",
			]
		descriptor += [
			"Charmed",
			"Corrupted",
			"Cranium",
			"Celestial",
			"Colossal",
			"Crafty",
			"Codex",
			"Colossal",
			"Complex",
			"Creativity",
			"Cosmic",
			"Cosmos",
			"Cosmic",
			"Cometary",
			"Climatic",
			"Cloud",
			"Chimeric",
			"Compassion",
			"Celestial",
			"Cold",
			"Chivalrous",
			"Chaotic",
			"Charcoal",
			"Charming",
			"Charter",
			"Chasm",
			"Compass",
			"Compassionate",
			"Concealed",
			"Confusion",
			"Constellation",
			"Contempt",
			"Copper",
			"Coral",
			"Corpse",
			"Cosmic",
			"Cosmos",
			"Covert",
			"Crater",
			"Crescent",
			"Crest",
			"Crested",
			"Crimson",
			"Crossed",
			"Crown",
			"Cruel",
			"Crypt",
			"Cryptic",
			"Crystal",
			"Crystalline",
			"Cunning",
			"Curse",
			"Cursed",
			"Cyan",
			"Cyclic",
			"Cyclonic",
			"Cyclopean",
			"Cynical",
			"Chronal",
			"Chronic",
			"Cipher",
			"Circus",
			"Citadel",
			"City",
			"Clairvoyant",
			"Clandestine",
			"Classical",
			"Comet",
			"Cleric",
			"Clerical",
			"Clever",
			"Cliff",
			"Climatic",
			"Cloaked",
			"Cloaked",
			"Clockwork",
			"Cloud",
			"Coast",
			"Cobalt",
			"Cobweb",
			"Code",
			"Cold",
			"Colonial",
			"Colossal",
			"Combat",
			"Candle",
			"Canyon",
			"Cardinal",
			"Castle",
			"Cat",
			"Catacomb",
			"Cathedral",
			"Cave",
			"Cavern",
			"Celestial",
			"Cloudreader",
			"Celtic",
			"Cerebral",
			"Cerulean",
			"Cerulean",
			"Chain",
			"Chained",
			"Chalice",
			"Champion",
			"Corrupt",
			"Chief",
			"Crowned",
			"Camouflage",
			"Cursed",
			"Charmbreaker",
			"Chaos",
			"Cerberus",
			"Clockwork",
			"Clockwork",
			"Charming",
			"Craft",
			"Chained",
			"Chain",
			"Chaos",
			"Crystal",
			"Cosmic",
			"Cosmic",
			"Cat",
			"Chain",
			"Chief",
			"Chief",
			"Chief",
			"Circus",
			"City",
			"Coral",
			"Copper",
			"Cursed",
			"Crimson",
			"Crown",
			"Cold",
			"Colossal",
			"Cooper",
			]
		descriptor += [
			"Dread",
			"Dimensional",
			"Dagger",
			"Deep Sea",
			"Dungeon",
			"Divine",
			"Dream",
			"Dusk",
			"Disgust",
			"Dauntless",
			"Dawn",
			"Deadly",
			"Death",
			"Deep",
			"Delightful",
			"Delta",
			"Desert",
			"Desolated",
			"Desperate",
			"Detestable",
			"Devoted",
			"Doom",
			"Dormant",
			"Draconian",
			"Draconic",
			"Dragon",
			"Dragonfire",
			"Drained",
			"Dream",
			"Dune",
			"Dungeon",
			"Dusk",
			"Dusky",
			"Dust",
			"Dynastic",
			"Day",
			"Divine",
			"Devotional",
			"Daemonic",
			"Dagger",
			"Dungeon",
			"Dark",
			"Darkness",
			"Darkstar",
			"Devout",
			"Dew",
			"Diabolical",
			"Diadem",
			"Dimension",
			"Dimensional",
			"Dire",
			"Damnation",
			"Drifting",
			"District", "Diavolical",
			"Doom",
			"Death",
			"Dawning", "Death",
			"Dominating",
			"Deadly",
			"Dragon", "Deadly", "Dawning",
			"Deep",
			"Divine",
			"Dream", "Dust",
			"Demon",
			"Deadly", "Desolate", "Deathless",
			]
		descriptor += [
			"Elder", "Existence", "Ethereal", "Eclipse", "Everlasting", "Eternal", "Eldritch", "Elder", "Elder", "Epochal", "Endless", "Ether", "Enemy", "Empty", "Everlasting", "Exalted", "Existence", "Exotic", "Expedition", "Extraterrestrial", "Exuberant", "Everlasting", "Eclipsed", "Ecliptic", "Ecstatic", "Ectoplasmic", "Edict", "Edo", "Erudite", "Esoteric", "Eternal", "Ethereal", "Euphoric", "Evanescent", "Evangelical", "Elder", "Eldritch", "Electric", "Elegant", "Elemental", "Elixir", "Elizabethan", "Eloquent", "Elusive", "Elven", "Elysian", "Elysium", "Ember", "Emblem", "Emerald", "Eminent", "Empathetic", "Enchanted", "Enchanting", "Energetic", "Energy", "Engine", "Enigma", "Enraged", "Envious", "Ephemeral", "Epochal", "Equinox", "Errant", "Erratic", "Echo", "Eagle", "Earth", "Ebony", "Ecclesiastical", "Eclipse", "Emissary", "Elemental", "Exalted", "Electric", "Ever", "Earth", "Earth", "Errant", "Energy", "Engine", "Equinox", "Enchanted", "Earthy", "Enchanted", "Evasive", "Eagle", "Equinox", "Energy", "Emerald", "Enchanted", "Engine", "Earth", "Errant", "Enchanted", "Enchanting", "Endless", "Earth", "Eternal", "Ethereal",
			]
		descriptor += [
			"Forgotten",
			"Ferocious",
			"Force",
			"Forest",
			"Forgotten",
			"Flowing",
			"Fluid",
			"Frostfire",
			"Frostbite",
			"Fire",
			"Frost",
			"Fen",
			"Fenrir",
			"Fable",
			"Fabled",
			"Fae",
			"Fairground", "Faithful", "Falcon", "Falcon",
			"Fallen",
			"Fanciful", "Fanged", "Far",
			"Fast", "Fathom", "Fearful",
			"Feathered", "Feral", "Ferocious",
			"Fluid", "Fervent", "Feudal", "Fierce", "Fiery", "Finned", "Folk",
			"Fool", "Forceful", "Foreboding", "Forest", "Forested", "Forge", "Formidable",
			"Fortress", "Fountain", "Frost", "Frostbound", "Frostbite", "Frostfire", "Frosty",
			"Frozen", "Frustrated", "Fuchsia", "Fullmetal", "Fullmoon", "Furious",
			"Furred", "Fury", "Future", "Ferocious",
			"Feral", "Fire", "Firebrand", "Firebreathing",
			"First", "Fjord", "Flame",
			"Flameheart", "Flamehearted", "Flametongue", "Flaming", "Fleshwork", "Floral", "Flourish", "Flowing", "Fluid", "Flying", "Fugitive", "Fire", "Fleshwork", "Force", "Flameborn", "Flesh", "Flying", "Forest", "Flame", "Flame", "Fullmetal", "Fleshwork", "First", "Forest", "Forest", "Fury", "Freedom", "Ferocious", "Fierce", "Free", "Freedom", "Fairy", "Fate", "Fateful", "Feathered", "Fiery", "Fire", "Fey",
			"Feywild", "Firbolg", "Fire", "Flame", "Frost", "False", "Forge",
			]
		descriptor += [
			"Green",
			"Godless",
			"Grim",
			"Giant",
			"Green",
			"Gold",
			"Gentle",
			"Great", "Glowing",
			"Gleaming", "Gloomy",
			"Grieving", "Grateful",
			"Graphite", "Granite",
			"Grail", "Green",
			"Golden", "Glowing",
			"Grail", "Gavel",
			"Gaseous",
			"Gases", "Gaseous",
			"Garden", "Gravitational",
			"Galactian", "Galactic",
			"Glacier", "Gothic",
			"Glacial", "Grail",
			"Goblet", "Glowing",
			"Great", "Grand",
			"Golden", "Gregorian",
			"Galactian", "Galactic",
			"Galaxy",
			"Gallant", "Garden",
			"Gargantuan", "Gargoyle", "Gaseous",
			"Gauntlet", "Gavel",
			"Gemmed", "Gentle",
			"Geyser", "Ghost",
			"Ghostly", "Gleaming",
			"Gloom", "Glorious",
			"Glowing",
			"Glyph", "Goblet",
			"Gold", "Golden",
			"Goldenhearted", "Goldenrod",
			"Golem", "Gorge",
			"Gorgonian", "Gothic",
			"Graceful", "Grail",
			"Grand", "Granite",
			"Graphite", "Grassland",
			"Grateful",
			"Grave",
			"Graveyard", "Gravitational",
			"Great", "Greathearted",
			"Green", "Gulf",
			"Grieving", "Grim",
			"Grimoire", "Grove",
			"Gryphon", "Grim",
			"Glorious", "Giant",
			"Gilded", "Glacial",
			"Glacier", "Glade",
			"Great", "Green",
			"Green", "Graceful",
			"Giant",
			"Golden", "Golden",
			"Golden",
			"Green", "Great",
			"Gentle", "Galactic",
			"Guarded", "Grizzly",
			"Godless",
			]
		descriptor += [
			"Hollow",
			"Hesperidean",
			"Heliospheric",
			"Historic",
			"Heroic",
			"Hell",
			"Hermetic",
			"Heart",
			"Harmonious",
			"Heartbroken",
			"Hourly",
			"Heartbroken",
			"Hourly",
			"Heartbroken",
			"Hunting",
			"Homeric",
			"Horned",
			"High",
			"Helian",
			"Haunting",
			"Harpist",
			"Harlequin",
			"Hidden",
			"Hoary",
			"High",
			"Holy",
			"Hamlet",
			"Hammer",
			"Han",
			"Harbinger",
			"Harbor",
			"Harlequin",
			"Harmony",
			"Harpist",
			"Harsh",
			"Hateful",
			"Haunting",
			"Heart",
			"Heartbroken",
			"Heath",
			"Heavenly",
			"Hedgerow",
			"Helian",
			"Heliospheric",
			"Hell",
			"Hellenistic",
			"Hellish",
			"Hermetic",
			"Hermitage",
			"Heroic",
			"Hex",
			"Hidden",
			"Hieratic",
			"High",
			"Hill",
			"Historic",
			"Hive",
			"Hoary",
			"Hollow",
			"Homeric",
			"Honorable",
			"Honored",
			"Hopeful",
			"Horizon",
			"Horned",
			"Horrific",
			"Horus",
			"Hostile",
			"Hourglass",
			"Hourly",
			"Hunter",
			"Hunting",
			"Hydra",
			"Hyperion",
			"Hypnotic",
			"Heretic",
			"Howling",
			"Hourglass",
			"Hunger",
			"Hell",
			"Hill",
			"High",
			"Hive",
			"Hound",
			"Hourglass",
			"Harmonic",
			]
		descriptor += [
			"Immortal", "Icy", "Inferno", "Instantaneous", "Intrepid", "Inquisitive", "Intellect", "Intellectual", "Inkwork", "Inkwell", "Ink", "Invincible", "Impenetrable", "Immortal", "Icarian", "Icicle", "Ice", "Icy", "Immemorial", "Infinite", "Immortal", "Indomitable", "Ink", "Ice", "Ion", "Ionic", "Ionized", "Irate", "Iridescent", "Iron", "Island", "Islet", "Isolated", "Ivory", "Icarian", "Ice", "Iceborn", "Icicle", "Icon", "Icy", "Idol", "Illusion", "Illusionist", "Imagination", "Imam", "Immemorial", "Immortal", "Impassioned", "Impenetrable", "Imperial", "Imperious", "Imperishable", "Impish", "Impulse", "Incan", "Incantation", "Indigo", "Inferno", "Infinite", "Infinity", "Inimical", "Ink", "Inkwell", "Inkwork", "Innovative", "Inquisitive", "Inscrutable", "Insidious", "Inspired", "Inspiring", "Instantaneous", "Intellect", "Intellectual", "Intense", "Interim", "Interstellar", "Intimate", "Intrepid", "Intriguing", "Invincible", "Iron", "Iron", "Ice", "Icicle", "Ink", "Ignoble", "Infernal", "Insatiable",
			]
		descriptor += [
			"Journey",
			"Jasmine",
			"Jackal",
			"Jackal",
			"Jasmine",
			"Jay",
			"Jester",
			"Journey",
			"Judge",
			"Juggernaut",
			"Jungle",
			"Juniper",
			"Jungle",
			"Just",
			"Just",
			"Judgmental",
			"Judgmental",
			"Judicial",
			"Just",
			"Justice",
			"Judicial",
			"Just",
			"Jurassic",
			"Jungle",
			"Jester",
			"Jade",
			"Jotunn",
			"Judicial",
			"Journey",
			"Jewel",
			"Jungle",
			"Jungle",
			"Jade",
			"Jealous",
			"Jewel",
			"Jewelcraft",
			"Jeweled",
			"Jotunn",
			"Joyous",
			"Jubilant",
			"Jungle",
			"Just",
			]
		descriptor += [
			"Knowledge", "Keep", "Krakenesque", "Knife",
			"Kaleidoscopic", "Keen", "Key", "Kind",
			"Kingly", "Knightly", "Kerberus", "Key",
			]
		descriptor += [
			"Loyal", "Lucky", "Lost", "Lonely", "Liquid", "Luminous", "Last", "Labyrinthine", "Labyrinth", "Labyrinth", "Large", "Legendary", "Legal", "Loving", "Luminous", "Lunar", "Lupine", "Lordly", "Laboratory", "Labyrinth", "Labyrinthine", "Lagoon", "Lake", "Lantern", "Last", "Lauded", "Lavender", "Law", "Liquid", "Leafy", "Luminous", "Learned", "Leechy", "Legendary", "Legislation", "Lethal", "Leviathan", "Leather", "Libra", "Library", "Lich", "Life", "Light", "Lightbringer", "Lightning", "Lionmane", "Lionheart", "Liquid", "Literary", "Lively", "Living", "Lizard", "Loathsome", "Lone", "Lonely", "Long", "Looming", "Lost", "Loving", "Loyal", "Luminous", "Lush", "Lustrous", "Luxurious", "Lycan", "Lyre", "Lyrist", "Lead", "Lonely", "Loyal", "Lingering", "Lore", "Lost", "Lost", "Life", "Luminous", "Life", "Lightning", "Lizard", "Lonely", "Long", "Leader", "Lunar", "Light", "Labyrinth", "Labyrinthine", "Lava",
			]
		descriptor += [
			"Master",
			"Magical",
			"Majestic",
			"Marsh",
			"Mischievous",
			"Mirthful",
			"Melancholic",
			"Mythical",
			"Moonlit",
			"Moon",
			"Mortal",
			"Memory",
			"Majestic",
			"Majestic",
			"Mystic",
			"Mad",
			"Misty",
			"Mighty",
			"Molten",
			"Masterful",
			"Monolith",
			"Monolithic",
			"Monstrous",
			"Moon",
			"Moonlit",
			"Moonshade",
			"Moonshadow",
			"Moss",
			"Motivated",
			"Mountain",
			"Mountainous",
			"Mournful",
			"Muddy",
			"Mulberry",
			"Museum",
			"Mutant",
			"Mysterious",
			"Mystery",
			"Mystic",
			"Mystical",
			"Mystique",
			"Mythic",
			"Mythical",
			"Mythological",
			"Maelstrom",
			"Magic",
			"Magma",
			"Magnetic",
			"Mahogany",
			"Majestic",
			"Maleficent",
			"Malevolent",
			"Malicious",
			"Malign",
			"Mammoth",
			"Mandrake",
			"Maned",
			"Mangrove",
			"Manticore",
			"Manticorian",
			"Mantle",
			"Marble",
			"Marine",
			"Maroon",
			"Marsh",
			"Marshy",
			"Martial",
			"Martian",
			"Marvelous",
			"Masked",
			"Masterful",
			"Mausoleum",
			"Mauve",
			"Maverick",
			"Maze",
			"Meadow",
			"Mecha",
			"Medallion",
			"Medieval",
			"Meditative",
			"Medusian",
			"Melancholic",
			"Melancholy",
			"Meld",
			"Melodic",
			"Memento",
			"Menacing",
			"Menagerie",
			"Mental",
			"Merciless",
			"Mercurial",
			"Meridian",
			"Merlinian",
			"Master",
			"Marine",
			"Mermaid",
			"Merry",
			"Mesopotamian",
			"Messianic",
			"Meteor",
			"Meteoric",
			"Meteoritic",
			"Metropolis",
			"Midnight",
			"Mighty",
			"Militant",
			"Millennial",
			"Mine",
			"Ministerial",
			"Minotaur",
			"Minotaurine",
			"Minstrel",
			"Miraculous",
			"Mirage",
			"Mirror",
			"Mirthful",
			"Mischievous",
			"Missionary",
			"Mist",
			"Mistral",
			"Malachite",
			"Mighty",
			"Moon",
			"Moonlit",
			"Mysterious",
			"Moon",
			"Mist",
			"Mind",
			"Mad",
			"Mad",
			"Magic",
			"Magma",
			"Marine",
			"Mental",
			"Mirror",
			"Mist",
			"Minotaur",
			"Moon",
			"Mutant",
			"Meteor",
			"Mythic",
			"Mythic",
			"Mighty",
			"Monstrous",
			"Monstrous",
			"Moonlight",
			]
		descriptor += [
			"Nomad",
			"Natural",
			"Nautical",
			"Notorious",
			"Nomadic",
			"Nocturnal",
			"Noble",
			"Nimble",
			"Nefarious",
			"Noble",
			"Nasty",
			"Nocturnal",
			"Noble",
			"Nimble",
			"Nefarious",
			"Nasty",
			"Nebular",
			"Notorious",
			"Nomadic",
			"Nocturnal",
			"Nimble",
			"Nefarious",
			"Noble",
			"Nordic",
			"Nemean",
			"Noble",
			"Nordic",
			"Nether",
			"Neon",
			"Nemesis",
			"Night",
			"Nocturnal",
			"Nova",
			"Nebulous",
			"Nature",
			"Night",
			"Night",
			"Nightmare",
			"Nasty",
			"Nautic",
			"Nebula",
			"Nebular",
			"Nebulous",
			"Nemean",
			"Nemesis",
			"Neon",
			"Nether",
			"Northern",
			"Neutron",
			"New",
			"Nexus",
			"Night",
			"Nightmare",
			"Nimble",
			"Nimbus",
			"Nirvana",
			"Nocturnal",
			"Nomadic",
			"Nordic",
			"Norman",
			"Notorious",
			"Nova",
			"Nun",
			"Natural",
			"Nature",
			"Nocturnal",
			"New",
			"New",
			"Nightmare",
			"Night",
			"Nocturnal",
			"Nebula Born",
			]
		descriptor += [
			"Orchid",
			"Ozone",
			"Old",
			"Old",
			"Other",
			"Old",
			"Oasis",
			"Oblivion",
			"Observatory",
			"Obsidian",
			"Obsolete",
			"Occult",
			"Ocean",
			"Oceanic",
			"Ochre",
			"Odious",
			"Offensive",
			"Old",
			"Olive",
			"Olympian",
			"Omen",
			"Ominous",
			"Omniscient",
			"Only",
			"Onyx",
			"Opal",
			"Opalescent",
			"Opposed",
			"Oppressive",
			"Optimistic",
			"Opulent",
			"Oracular",
			"Orange",
			"Orb",
			"Orbit",
			"Orbital", "Orbiting", "Orchard", "Orchid", "Orphean", "Otherworldly", "Outlandish",
			"Outpost", "Outraged", "Outrageous", "Overgrown",
			"Overlord", "Owl", "Ozone", "Order", "Oceanic", "Orange", "Old", "Otherworld",
			]
		descriptor += [
			"Power",
			"Phantom",
			"Prismatic",
			"Prehistoric",
			"Petrifying",
			"Petrified",
			"Perplexing",
			"Pensive",
			"Political",
			"Polar",
			"Primordial",
			"Perpetual",
			"Perennial",
			"Purifying",
			"Pure",
			"Primeval",
			"Plague",
			"Pain",
			"Palace",
			"Pathfinder",
			"Patriarch",
			"Patriarchal",
			"Paw",
			"Peaceful",
			"Pearl",
			"Pearlescent",
			"Peat",
			"Pendant",
			"Pensive",
			"Perceptive",
			"Peregrine",
			"Perennial",
			"Perilous",
			"Perpetual",
			"Petal",
			"Petrified",
			"Phalanx",
			"Phantasm",
			"Phantasmagorical",
			"Phantasmal",
			"Phantom",
			"Pharaonic",
			"Pharaonic",
			"Philosophical",
			"Phlegmatic",
			"Phoenix",
			"Phoenixian",
			"Phylactery",
			"Pietistic",
			"Pillar",
			"Pine",
			"Pinnacle",
			"Pioneering",
			"Piqued",
			"Placid",
			"Plague",
			"Planar",
			"Planetary",
			"Plasma",
			"Plateau",
			"Platinum",
			"Pleasant",
			"Plucky",
			"Plum",
			"Poet",
			"Poignant",
			"Poisonous",
			"Polar",
			"Pond",
			"Ponderous",
			"Pontifical",
			"Poppy",
			"Porcelain",
			"Port",
			"Potent",
			"Potion",
			"Powder",
			"Power",
			"Poker",
			"Powerhouse",
			"Prairie",
			"Plague",
			"Precious",
			"Precocious",
			"Predatory",
			"Preternatural",
			"Primal",
			"Prime",
			"Primeval",
			"Primordial",
			"Princely",
			"Prismatic",
			"Prison",
			"Private",
			"Profound",
			"Prohibition",
			"Promethean",
			"Prophetic",
			"Prosperous",
			"Protected",
			"Proud",
			"Psion",
			"Pugnacious",
			"Pulsar",
			"Pulsating",
			"Pumpkin",
			"Pungent",
			"Punk",
			"Pure",
			"Purifying",
			"Purist",
			"Purple",
			"Puzzled",
			"Pyramid",
			"Pyro",
			"Palm",
			"Pandemonium",
			"Panicked",
			"Papal",
			"Paradox",
			"Paradoxical",
			"Parched",
			"Parish",
			"Park",
			"Parliament",
			"Passionate",
			"Pack",
			"Phantom",
			"Primal",
			"Pillager",
			"Power",
			"Powerful",
			"Pain",
			"Pack",
			"Pain",
			"Pure",
			"Plague",
			"Primal",
			"Prehistoric",
			"Primigenial",
			"Primordial",
			"Proud",
			"Planar",
			]
		descriptor += [
			"Quest",
			"Quicksand",
			"Quantum",
			"Quartz",
			"Quasar",
			"Quest",
			"Questing",

			"Quick",
			"Quicksand",
			"Quicksilver",
			"Quiet",
			"Quill",
			"Quicksilver",
			]
		descriptor += [
			"Requiem",
			"Rebellion",
			"Rugged",
			"Runic",
			"Relentless",
			"Rogue",
			"Risen",
			"Restless",
			"Requiem",
			"Relic",
			"Rippling",
			"Reality",
			"Raging",
			"Radiant",
			"Rhythm",
			"Rising",
			"Raging",
			"Ragnarok",
			"Rain",
			"Renegade",
			"Rule",
			"Rune",
			"Rainbow",
			"Rainforest",
			"Rainstorm",
			"Rampant",
			"Rampart",
			"Ranch",
			"Rising",
			"Rose",
			"Restless",
			"Red",
			"Rosethorn",
			"Raid",
			"Red",
			"Red",
			"Rule",
			"Rat",
			"Rational",
			"Ravaged",
			"Ravaging",
			"Radiant",
			"Reality",
			"Reckless",
			"Reckoner",
			"Reckoning",
			"Reclusive",
			"Red",
			"Redoubtable",
			"Redwood",
			"Reef",
			"Refined",
			"Regal",
			"Regulation",
			"Relaxed",
			"Relentless",
			"Relic",
			"Remnant",
			"Remote",
			"Renaissance",
			"Renegade",
			"Reptilian",
			"Repugnant",
			"Resentful",
			"Resilient",
			"Resolute", "Resounding",
			"Resplendent",
			"Revered",
			"Reverent",
			"Rhapsodic", "Radiant", "Rhombus",
			"Ribbon",
			"Rich",
			"Riddle", "Ridge", "Rift",
			"Righteous", "Rime", "Rippling", "River", "Riverine",
			"Roaming", "Robotic", "Rock", "Rocky", "Rod",
			"Rogue", "Roman", "Rooted", "Rosaline", "Rose",
			"Rosy", "Royal", "Ruby", "Rugged", "Ruined",
			"Ruins", "Rule", "Rune", "Runecarved",
			"Runewielder", "Runic", "Rural", "Rust", "Rustic",
			"Rusty", "Ruthless", "Rune", "Rune", "Red", "Rainstorm", "Red", "River", "Rogue", "Rune", "Riding", "Roaring",
			]
		descriptor += [
			"Starship",
			"Shadow",
			"Silver",
			"Star",
			"Shining",
			"Structures",
			"Stellar",
			"States",
			"Supernova",
			"Sunset",
			"Sunny",
			"Sun",
			"Starry",
			"Star",
			"Space",
			"Silvertongued",
			"Sempiternal",
			"Sorrel",
			"Swan",
			"Stormchaser",
			"Stingray",
			"Starship",
			"Strength",
			"Sunblessed",
			"Sun",
			"Shadow",
			"Secret",
			"Supreme",
			"Strong",
			"Supreme",
			"Star",
			"Sylvan",
			"Shadow",
			"Sacred",
			"Subterranean",
			"Solemn",
			"Sorrow",
			"Mourning",
			"Grief",
			"Solar",
			"Spirit",
			"Shade",
			"Stalker",
			"Stargazer",
			"Stellar",
			"Sublime",
			"Slaying",
			"Saga",
			"Sagacious",
			"Saint",
			"Sanctuary",
			"Sand",
			"Sandy",
			"Sanguine",
			"Sanskrit",
			"Sapphire",
			"Satellite",
			"Satyric",
			"Savanna",
			"Savannah",
			"Savant",
			"Savvy",
			"Scaled",
			"Scarab",
			"Scarlet",
			"Scenic",
			"Scent",
			"Scholar",
			"School",
			"Science",
			"Scientific",
			"Scintillating",
			"Scion",
			"Scorching",
			"Scroll",
			"Sea",
			"Seal",
			"Seashore",
			"Seasonal",
			"Secluded",
			"Second",
			"Secret",
			"Secretive",
			"Skeletal",
			"Mercenary",
			"Seductive",
			"Seismic",
			"Selenian",
			"Sempiternal",
			"Sensual",
			"Sentimental",
			"Seraphic",
			"Serene",
			"Serpentine",
			"Seventh",
			"Sewer",
			"Seychelle",
			"Shade",
			"Shaded",
			"Shadow",
			"Shadowy",
			"Shallow",
			"Shamanic",
			"Shark",
			"Shattered",
			"Shattering",
			"Shield",
			"Shielded",
			"Shimmering",
			"Shining",
			"Shivering",
			"Shore",
			"Shrewd",
			"Shrine",
			"Sickly",
			"Sienna",
			"Sigil",
			"Silent",
			"Silver",
			"Silvertongued",
			"Simian",
			"Singing",
			"Sinister",
			"Siren",
			"Sirenian",
			"Sirenic",
			"Skeleton",
			"Sky",
			"Skyborn",
			"Skyborn",
			"Slate",
			"Sleeping",
			"Slimey",
			"Sly",
			"Smart",
			"Soul",
			"Soulbound",
			"Soulfire",
			"Soulful",
			"Space",
			"Spark",
			"Spartan",
			"Spectral",
			"Spell",
			"Spellbound",
			"Spined",
			"Spiral",
			"Spire",
			"Spiritual",
			"Spiteful",
			"Splendid",
			"Spring",
			"Sprouting",
			"Stadium",
			"Staff",
			"Stalwart",
			"Standard",
			"Star",
			"Star-born",
			"Star-crossed",
			"Star-crosser",
			"Starborn",
			"Starcrossed",
			"Starcrosser",
			"Starfall",
			"Starlit",
			"Starry",
			"Stars",
			"Starting",
			"Statute",
			"Steadfast",
			"Stealthy",
			"Steam",
			"Steamy",
			"Steelhearted",
			"Stellar",
			"Stern",
			"Stinger",
			"Stoic",
			"Stone",
			"Storm",
			"Stormbringer",
			"Stormcaller",
			"Stormy",
			"Strait",
			"Strategist",
			"Stratospheric",
			"Stream",
			"Strong",
			"Sea",
			"Stunning",
			"Stygian",
			"Sublime",
			"Subterranean",
			"Subtle",
			"Sulfuric",
			"Sullen",
			"Summer",
			"Sun",
			"Sunborn",
			"Sunder",
			"Sunflare",
			"Sunlit",
			"Sunny",
			"Sunset",
			"Sunstone",
			"Superb",
			"Supernatural",
			"Supernova",
			"Supreme",
			"Suspicious",
			"Swamp",
			"Swampy",
			"Sweet",
			"Swift",
			"Sympathetic",
			"Synthesis",
			"Star",
			"Star",
			"Silent",
			"Stealth",
			"Sea",
			"Shadow",
			"Smoke",
			"Shelled",
			"Snowy",
			"Solar",
			"Solstice",
			"Sophisticated",
			"Sorcery",
			"Sorrowful",
			"Stone",
			"Sky",
			"Slinking",
			"Scorched",
			"Supreme",
			"Spell",
			"Spark",
			"Star",
			"Storm",
			"Skull",
			"Spark",
			"Sylvan",
			"Sylvan",
			"Solstice",
			"Sand",
			"Sand",
			"Seventh",
			"Second",
			"Stone",
			"Silver",
			"Silk",
			"Science",
			"Shadow",
			"Scale",
			"Smoke",
			"Sneaky",
			"Spring",
			"Steam",
			"Storm",
			"Starting",
			"Star",
			"Strong",
			"Spark",
			"Spell",
			"Solar",
			"Summer",
			"Spirit",
			"Starry",
			"Stellar",
			"Sacred",
			"Soul",
			"Solar",
			"Steel",
			"Spirit",
			]
		descriptor += [
			"Tireless",
			"Treasure", "Treasure",
			"Thorn", "Twisted",
			"Talisman", "Thorn",
			"Timeless", "Temporal",
			"Timebender", "Time",
			"Traditional", "Timeless",
			"Timely", "True",
			"Tenacity", "Treasure",
			"Tomb", "Time",
			"Tomb",
			"Tormented",
			"Tempest", "Troll", "Talisman",
			"Tigerstrip", "Time",
			"Timeless", "Time",
			"Titanic", "Token",
			"Tomb", "Trick", "Topaz", "Torch",
			"Totem",
			"Town", "Traditional",
			"Trail", "Trance",
			"Tranquil", "Transcend",
			"Transcendent", "Transient", "Traveling", "Treacherous",
			"Tremendous", "Tribal", "Tribe", "Tribunal",
			"Trickster", "Trojan", "Tropical", "True",
			"Tudor", "Tulip", "Tundra",
			"Turbulent", "Turquoise", "Turtle", "Twilight",
			"Twisted", "Typhoon", "Talon", "Tangerine",
			"Tartarean", "Taupe", "Tavern", "Teal",
			"Tectonic", "Tempest", "Tempestuous", "Temple",
			"Temporal", "Tenacious", "Tender", "Tentacled", "Terra", "Terrifying", "Thaumaturge", "Theater", "Theocratic", "Thicket", "Third", "Thorn", "Thorny", "Thousand", "Threatening", "Thunder", "Thundering", "Thunderous", "Tidal", "Tide", "Timeless", "Thorn", "Talisman", "Threatening", "Time", "Time-bender", "Timebender", "Timeless", "Titanic", "Twilight", "Terrifying", "Terrorific", "True", "Tower", "Thunder", "Thunder", "Tomb", "Third", "Trival", "Thunder", "Terrifying", "Treasure", "Throne", "Tide", "Time", "Timeless",
			]
		descriptor += [
			"Unholy",
			"Unnatural",
			"Urban",
			"Unyielding",
			"Untamed",
			"Underdark",
			"Underworld",
			"Undying",
			"Unearthly",
			"Unfathomable",
			"Unflinching",
			"Unforgiving",
			"Unhappy",
			"Universal",
			"Universe",
			"Unrevealed",
			"Unseen",
			"Unstoppable",
			"Untamed",
			"Unyielding",
			"Uplifting",
			"Uranian",
			"Ursine",
			"Utopic",
			"Ultimate",
			"Ultra",
			"Ultra",
			"Ultraviolet",
			"Unassailable",
			"Unbound",
			"Unbreakable",
			"Uncharted",
			"Unconquerable",
			"Undaunted",
			"Undertow",
			"Unholy",
			"Underworld",
			"Underground",
			]
		descriptor += [
			"Vengeful",
			"Voltaic",
			"Venerable",
			"Venom",
			"Venom",
			"Venomous",
			"Verdant",
			"Vicious",
			"Vigilant",
			"Vigorous",
			"Virtuous",
			"Volcano",
			"Volcanic",
			"Voided",
			"Void",
			"Vintage",
			"Venerable",
			"Victorian",
			"Valor",
			"Valiant",
			"Valkyrian",
			"Valkyrie",
			"Valley",
			"Valor",
			"Vampiric",
			"Vanirian",
			"Vault",
			"Vapor",
			"Vaporous",
			"Vase",
			"Veiled",
			"Victorious",
			"Vigilant",
			"Viking",
			"Village",
			"Villainous",
			"Vindicator",
			"Vindictive",
			"Vine",
			"Vintage",
			"Violent",
			"Violet",
			"Viridian",
			"Virtuous",
			"Virulent",
			"Visage",
			"Visionary",
			"Vitriolic",
			"Void",
			"Voidborne",
			"Voided",
			"Voidless",
			"Volatile",
			"Volcanic",
			"Volcano",
			"Voracious",
			"Vortex",
			"Vulcanian",
			"Vulpine",
			"Void",
			"Void",
			"Void",
			"Vengeance",
			"Vellum",
			"Vendetta",
			"Venerable",
			"Vengeance",
			"Vengeful",
			"Venomous",
			"Valiant",
			"Venusian",
			"Verdant",
			"Vermilion",
			"Vernal",
			"Vertex",
			"Vesper",
			"Vesperal", "Vessel",
			"Veteran", "Vibrant", "Vicar", "Vicious",
			"Violet", "Valiant", "Vampiric", "Veteran",
			"Venom", "Vicious", "Volcanic", "Venom",
			]
		descriptor += [
			"Whitescale",
			"Whisper",
			"Waterwind",
			"Walking",
			"Wandering",
			"Wealth",
			"War",
			"Waterborn",
			"Water",
			"Water",
			"Wave",
			"Whim",
			"Whisper",
			"Wholesome",
			"Wild",
			"Windborn",
			"Wind",
			"Windborn",
			"Winged",
			"Winter",
			"Wooden",
			"Wisdom",
			"Witch",
			"Wise",
			"Winterborn",
			"Wolf",
			"Wrathful",
			"Witty", "Wandering",
			"White", "War",
			"Wormhole", "Warp",
			"Winter", "Windy", "Wind",
			"Wailing", "Wind",
			"Wild", "Wind",
			"Wood", "Wand", "Wave", "Wandering", "War", "Warp", "Warping", "Wary", "Water", "Watery", "Wave", "Wavy", "Weapon", "Weatherlight", "Web", "Western", "Whale", "Whimsy", "Whirlwind", "Whispering", "Whistle", "White", "Wicked", "Wight",
			"Wild",
			"Wilderness",
			"Wildfire", "Willow", "Windy", "Winged", "Winter", "Winterborn", "Wise", "Wisp", "Witchy", "Withering", "Witted", "Wondrous", "Woodland", "Woods", "Woody",
			"World", "Wormhole", "Wrathful", "Woodland", "Wind", "White", "Water", "War", "Warp", "War", "Warping", "Water", "White", "Wise", "Wind", "Winter",
			"Wild", "Wolf", "Wind",
			"Wild", "Wicked",
			]
		descriptor += [
			"X-Ray",
			"Xenolith",

			"Xenon",
			]
		descriptor += [
			"Yearning",
			"Yesteryear",

			"Youthful",
			"Yellow",
			]
		descriptor += [
			"Zephyr",
			"Zodiacal",
			"Zodiac",
			"Zombie",
			"Zealot",
			"Zealous",
			"Zen",
			"Zenith",
			"Zephyr",

			"Zephyrian",
			"Zestful",
			"Zeusian",
			"Zodiac",
			"Zodiacal",
			"Zone",
			"Zoo",
			"Zypher",
			"Zombie",
			]
	except:
		descriptor += [
			"Dark",
			]

	if "Barbarian" in genus:
		descriptor += [
			"Frantic",
			"Raging",
			"Wild",
			"Fierce",

			"Savage",
			"Untamed",
			"Mighty",
			]
	if "Berserker" in genus:
		descriptor += [
			"Frantic", "Raging",
			"Wild",
			"Frenzy", "Unstoppable",
			"Fury",
			"Fierce", "Savage",
			"Untamed",
			"Mighty", "War",
			"Warrior",
			]
	if "Cultist" in genus:
		descriptor += [
			"Celestial", "Cult",
			"Fanatical",
			"Friar",
			"Mystical", "Secret",
			"Zealous",
			"Obscure",
			]
	if "Charlatan" in genus:
		descriptor += [
			"Deception",
			"Charm",
			"Charmming",
			"Sly",

			"Smooth",
			"Stylish",
			"Wealthy",
			"Word",
			]
	if "Commoner" in genus:
		descriptor += [
			"Honest",
			"Modest",

			"Village",
			]
	if "Crafter" in genus:
		descriptor = [
			"Voltaic",
			"Mender",
			"Master",
			"Skillful",

			"Artisanal",
			"Dexterous",
			"Inventive",
			]
	if "Criminal" in genus:
		descriptor += [
			"Barber",
			"Mercenary",
			"Crime",
			"Underworld",
			"Sneaking",

			"Sneaky",
			"Ruthless",
			"Shade",
			"Shady",
			"Clever",
			]
	if "Cleric" in genus:
		descriptor += [
			"Sun",
			"Sun",
			"Sun",
			"Sacred",
			"Sacred",
			"Hallowed",

			"Dawn",
			"Dawn",
			"Radiant",
			"Celestial",
			"Oracular",
			"Penitent",
			]
	if "Druid" in genus:
		descriptor += [
			"Tusked",
			"Jungle",
			"Natural",
			"Earthy",
			"Mystical",

			"Primal",
			"Guardian",
			"Green",
			"Fern",
			]
	if "Expert" in genus:
		descriptor += [
			"Historic",
			"Knowledge",

			"Skill",
			]
	if "Explorer" in genus:
		descriptor += [
			"Adventure",
			"Brave",
			"Daring",
			"Jungle",
			"Migratory",

			"Nomadic",
			"Nomad",
			"Roaming",
			"Traveling",
			"Wandering",
			]
	if "Fighter" in genus:
		descriptor += [
			"Mercenary",
			"Battle",
			"Battle",

			"Battleground",
			"War",
			]
	if "Guardian" in genus:
		descriptor += [
			"Guardan",
			"Guarding",
			"Protector",

			"Alert",
			"Discipline",
			"Protector",
			]
	if "Healer" in genus:
		descriptor += [
			"Celestial",
			"Compassion",
			"Heal",

			"Wise",
			"Care",
			]
	if "Hero" in genus:
		descriptor += [
			"Celestial",
			"Valiant",
			"Brave",

			"Heroic",
			"Gallant",
			]
	if "Hunter" in genus:
		descriptor += [
			"Jungle",
			"Green",
			"Stealth",
			"Rugged",

			"Trapper",
			"Wild",
			"Gloom",
			]
	if "Knight" in genus:
		descriptor += [
			"Chivalrous",
			"Gallant",
			"Golden",

			"Honorable",
			"Bold",
			"Cavalier",
			]
	if "Monk" in genus:
		descriptor += [
			"Monastery",
			"Monastic",
			"Artisan",
			"Grace",
			"Celestial",
			"Urn",

			"Discipline",
			"Spiritual",
			"Meditative",
			"Ascetic",
			"Harmony",
			]
	if "Merchant" in genus:
		descriptor += [
			"Shrewd",
			"Wealthy",
			"Trading",

			"Skilled",
			"Resourceful",
			"Prosperous",
			]
	if "Noble" in genus:
		descriptor += [
			"Kingly",
			]
	if "Pirate" in genus:
		descriptor += [
			"Ruthless",
			"Swashbuckling",
			"Seafaring",
			"Rebel",

			"Infamous",
			"Treasure",
			"Booty",
			"Dock",
			]
	if "Traveler" in genus:
		descriptor += [
			"Migratory",
			"Nomadic",
			"Nomad",
			"Roaming",

			"Traveling",
			"Wandering",
			"Circus",
			]
	if "Trickster" in genus:
		descriptor += [
			"Surviving",
			"Quick",
			"Lonely",
			"Resourceful",
			"Scrappy",

			"Streetwise",
			"Surviving",
			"Scrappy",
			"Quick",
			]
	if "Priest" in genus:
		descriptor = [
			"Celestial",
			"Chapel",
			"Clerical",
			"Devout",

			"Faithful",
			"Holy",
			"Pious",
			"Sacred",
			]
	if "Ranger" in genus:
		descriptor += [
			"Troll",
			"Troll",
			"Troll",
			"Wild",
			"Wild",
			"Thorn",
			"Thorn",
			"Hollow",
			"Beast",

			"Green",
			"Jungle",
			"Wilderness",
			"Tracking",
			"Survivalist",
			"Rugged",
			"Master",
			"Survival",
			"Rugged",
			]
	if "Rogue" in genus:
		descriptor += [
			"Sneaky",
			"Masterful",
			"Cunning",
			"Agile",

			"Mysterious",
			"Resourceful",
			"Shady",
			"Shadow",
			]
	if "Scholar" in genus:
		descriptor += [
			"Learned",
			"Intellectual",
			"Studious",

			"Erudite",
			"Inquisitive",
			]
	if "Soldier" in genus:
		descriptor += [
			"Veteran",
			"War",
			"Battle",
			"Hardened",
			"Strategic",
			"Brave",
			"Tactical",
			"Special",

			"Tactical",
			"Brave",
			"Last",
			"First",
			"Battle",
			"Hardened",
			"Hierarchy",
			"Strategist",
			]
	if "Shaman" in genus:
		descriptor += [
			"Green",
			"Jungle",
			"Spiritual",
			"Mystic",
			"Oracular",

			"Elemental",
			"Tribal",
			"Ancestral",
			"Shamanic",
			]
	if "Spy" in genus:
		descriptor += [
			"Spy",
			"Undercover",
			"Covert",
			"Undercover",
			"Secret",
			"Stealthy",

			"Infiltrating",
			"Covert",
			"Undercover",
			"Secret",
			"Stealthy",
			"Infiltrating",
			]
	if "Traveler" in genus:
		descriptor += [
			"Jungle",
			"Wandering",
			"Adventure",

			"Nomad",
			"Curious",
			"World",
			]
	if "Witch" in genus:
		descriptor += [
			"Enchanting",
			"Hexing",
			"Mystical",

			"Occult",
			"Wise",
			]
	if "Wizard" in genus:
		descriptor += [
			"Rune",
			"Rune",
			"Rune",
			"Spell",
			"Spell",
			"Void",

			"Star",
			"Star",
			"Arcane",
			"Knot",
			"Oracular",
			"Cryptic",
			]

	if "Aberration" in genus:
		descriptor += [
			"Abhorrent", "Starship",
			]
		if "Githzerai" in genus:
			descriptor += [
				"Enlightened", "Zen",
				"Mystic",
				"Ascetic",
				"Spiritual",
				"Harmonious",
				"Harmony",
				]
		if "Githyanki" in genus:
			descriptor += [
				"Marauding",
				"Conquering",
				"War",

				"Ruthless",
				"Dominant",
				]
		if "Destiny Devouers" in genus:
			descriptor += [
				"Oracle",
				"Time",
				"Body",
				"Destiny",
				"Fate",
				"Chrono",
				"Fate",

				"Traveling",
				"Temporal",
				"Altered",
				"Shattered",
				"Future",
				"Swapping",
				]
		if "Parasyte" in genus:
			descriptor += [
				"Parasitic", "Infestation",
				"Mind", "Control",
				"Body", "Snatcher",
				"Host", "Taker",
				"Infested", "Infesting",
				"Neural",
				]
		if "Alien Spawn" in genus:
			descriptor += [
				"Celestial",
				"Galactic",
				"Extraterrestrial",
				"Distant",

				"Alien",
				"Outer",
				"Unearthly",
				"Starborne",
				]
		if "Chaos Warper" in genus:
			descriptor += [
				"Star",
				"Galactic",
				"Cosmic",
				"Nebula",
				"Golden",
				"Cosmic",
				"Starborn",

				"Astral",
				"Nebulous",
				"Galactic",
				"Nebula",
				"Star",
				"Galaxy",
				]
		if "Symbioid" in genus:
			descriptor += [
				"Symbioitic",
				"Communing",
				]
	if "Aven" in genus:
		descriptor += [
			"Celestial", "Sky",
			"Feathered",
			"Aerial",
			]
		if "Owlin" in genus:
			descriptor += [
				"Nocturnal",
				"Wise",
				"Silent",
				"Moon",

				"Feathered",
				"Stargazer",
				"Night",
				"Star",
				]
		if "Raptoran" in genus:
			descriptor += [
				"Mountain",
				"Falcon",
				"Windsoarer",
				"Cliffdweller",
				"Wingwarrior",
				"Highflyer",
				"Cliff",
				"Sky",
				"Peak",
				"Windrider",
				"Aerie",
				]
		if "Aarakocra" in genus:
			descriptor += [
				"Soaring",
				"Spiritual",
				"Windrider",
				"Feather",
				"Skydancer",
				]
		if "Kenku" in genus:
			descriptor += [
				"Mimicking",
				"Crafty",
				"Raven",
				"Streetwise",
				"Scheming",
				]
		if "Birdfolk" in genus:
			descriptor += [
				"Flock",
				"Nest",

				"Wing",
				"Feathered",
				]
		if "Avens" in genus:
			descriptor += [
				"Avian", "Golden",
				"Red",
				"Sky",
				"Feathered",
				"Yellow", "Wing",
				"Skybound",
				"Winged",
				"Flight",
				"Wind", "Feathered",
				"Aerial",
				"Aerie",
				"Soaring",
				]
		if "Tengu" in genus:
			descriptor += [
				"Mystical", "Ancient",
				"Folkloric",
				"Martial",
				"Wise",
				"Trickster",
				"Mystic",
				"Raven",
				"Kenshi",
				"Master",
				"Lore",
				"Shadow",
				]
	if "Beast" in genus:
		descriptor += [
			"Tailed",
			"Tusked",

			"Wild",
			]
		if "Kong" in genus:
			descriptor += [
				"Kong",
				"Silverback",
				"Colossal",
				"Jungle",
				"Mighty",
				"Fierce",
				"Vigilant",

				"Primal",
				"Island",
				"Ancient",
				"Titan",
				"Colossal",
				"Untamed",
				]
		if "Armored Bear" in genus:
			descriptor += [
				"Bear",
				"Iron",
				"Armor",
				"Ice",
				"Claw",

				"Northern",
				"Claw",
				"Stalwart",
				"Ursine",
				"Ursa",
				]
		if "Giant Eagle" in genus:
			descriptor += [
				"Celestial",
				"Majestic",
				"Sky",
				"Soaring",
				"Keen",
				"Eagle",
				"Sky",
				"Wing",
				"Aerial",
				"Feather",
				]
		if "Tiger" in genus:
			descriptor += [
				"White", "Feline",
				"Silent",
				"Fierce",
				"Snow", "Mystic",
				"Alabaster",
				"Stealth",
				"Silent", "Snow",
				"Frost",
				"Amber",
				]
		if "Vulture Spirit" in genus:
			descriptor += [
				"Celestial",
				"Carrion",
				"Death",
				"Spirit",
				"Sight",
				"Scavenger",
				]
		if "Deer Spirit" in genus:
			descriptor += [
				"Amber",
				"Forest",
				"Gentle",
				"Graceful",
				"Spirit",

				"Gentle",
				"Nature",
				"Woodland",
				"Whispering",
				"Gentle",
				]
		if "Owl" in genus:
			descriptor += [
				"Ancient",
				"Night",
				"Silent",

				"Mystic",
				"Wise",
				]
		if "Lion" in genus:
			descriptor += [
				"Feline",
				]
	if "Celestial" in genus:
		descriptor += [
			"Amber",
			"Astral",
			"Blessed",
			"Celestial",
			"Divine",
			"Ethereal",
			"Fire",
			"Flame",
			"Golden",
			"Green",
			"Heavenly",
			"Radiant",
			"Sacred",
			"Shadow",
			"Sky",

			"Sublime",
			"Yellow",
			"Luminous",
			"Celestial",
			"Darkness",
			"Divine",
			"Ethereal",
			"Flame",
			"Golden",
			"Green",
			"Heavenly",
			"Radiant",
			"Shadow",
			"Sky",
			]
		if "Planetar" in genus:
			descriptor += [
				"Mighty", "Divine",
				"Radiant",
				"Just",
				]
		if "Angelic Bloodline" in genus:
			descriptor += [
				"Born",
				"Touched",
				]
	if "Construct" in genus:
		descriptor += [
			"Electrostatic", "Puppeteer", "Clockwork",
			"Living", "Titanium", "Iron",
			"Steel", "Palladium",
			]
	if "Dwarf" in genus:
		descriptor += [
			"Anvil",
			"Forge",
			"Deep",
			"Stone",

			"Rune",
			"Clan",
			"Dwarven",
			"Tunnel",
			]
	if "Dragon" in genus:
		descriptor += [
			"Tailed", "Draconic",
			"Dragon",
			"Dragon", "Dragon",
			"Dragon",
			]
		if "Wyrm" in genus:
			descriptor += [
				"Serpentine",
				]

		if "Silver" in genus:
			descriptor += [
				"Silver",
				"Quicksilver",

				"Metal",
				"Metallic",
				]
	if "Elf" in genus:
		descriptor += [
			"Star",
			"Moon",
			"Silver",
			"Glimmer",
			"Leaf",
			"Exquisite",

			"Thorn",
			"Elven",
			"Elven",
			"Elven",
			"Elven",
			"Elvish",
			]
	if "Fiend" in genus:
		descriptor += [
			"Tailed", "Fiendish",
			"Hellish",
			"Satanic",
			]
	if "Fae" in genus:
		descriptor += [
			"Vendilion",
			]
	if "Giant" in genus:
		descriptor += [
			"Troll",
			"Stone",
			"Peak",
			"Mountain",

			"Boulder",
			"Gigantic",
			"Roaring",
			]
	if "Gnome" in genus:
		descriptor += [
			"Gnomish",
			]
	if "Goblin" in genus:
		descriptor += [
			"Knot",
			"Knot",
			"Cave",
			"Grease",

			"Trick",
			"Shadow",
			"Sly",
			"Scrap",
			]
	if "Human" in genus:
		descriptor += [
			"Mortal",
			]

	if "Halfling" in genus:
		descriptor += [
			"Plucky",
			]
	if "Orc" in genus:
		descriptor += [
			"Tusked",
			"Green",
			"Green Skin",

			"Greenblood",
			"Emerald",
			]
	if "Ooze" in genus:
		descriptor += [
			"Bituminous",
			"Amber",
			]
	if "Plant" in genus:
		descriptor += [
			"Spore",
			"Treefolk",

			"Green",
			]
		if "Dryad" in genus:
			descriptor += [
				"Dryad",
				]
	if "Undead" in genus:
		descriptor += [
			"Undying",
			"Deathless",
			"Grave",
			"Sepulchral",
			"Necrotic",
			"Withered",
			"Hollow",
			"Cadaverous",

			"Pallid",
			"Restless",
			"Mournful",
			"Shrouded",
			"Grim",
			"Eternal",
			"Cursed",
			"Spectral",
			]
		if "Skeleton" in genus:
			descriptor += [
				"Bone", "Rattling",
				"Fleshless",
				"Marrowless",
				]
		elif "Zombie" in genus:
			descriptor += [
				"Rotting", "Shambling",
				"Putrid",
				"Decaying",
				]
		elif "Ghost" in genus or "Spectre" in genus or "Spirit" in genus:
			descriptor += [
				"Phantom", "Wailing",
				"Ethereal",
				"Haunting",
				]
		elif "Wraith" in genus or "Wight" in genus:
			descriptor += [
				"Shadowed",
				"Gravebound",
				"Soulchilled",
				]
		elif "Lich" in genus:
			descriptor += [
				"Phylactered", "Soulcaged",
				"Dreadful",
				"Arcane",
				]
		elif "Mummy" in genus:
			descriptor += [
				"Bandaged",
				"Embalmed",

				"Ancient",
				"Desiccated",

				"Mummified",
				]
		elif "Revenant" in genus:
			descriptor += [
				"Vengeful",

				"Returned",

				"Oathbound",
				]
		elif "Ghoul" in genus:
			descriptor += [
				"Ravenous",
				"Carrion",

				"Gravehungry",
				"Graveborn",
				]
	if "Vampire" in genus:
		descriptor += [
			"Blood",
			"Blood",
			"Blood",
			"Night",
			"Night",
			"Nocturnal",
			"Crimson",
			"Pale",

			"Sanguine",
			"Bloodcursed",
			"Bloodsoaked",
			"Vampiric",
			"Dark Sun",
			"Sun",
			"Sun",
			"Bloodtithe",
			]
	if "Sun Scarab" in genus:
		descriptor += [
			"Amber",
			"Ancient",
			"Astral",
			"Eternal",
			"Gold",
			"Golden",

			"Radiant",
			"Resilient",
			"Sacred",
			"Solar",
			"Yellow",
			]
	if "Eosian" in genus:
		descriptor += [
			"Dawnbringer",
			"Daybreak",
			"Daylight",
			"Ethereal",
			"Luminous",

			"Morning",
			"Radiant",
			"Solar",
			"Sunlit",
			"Sunrise",
			]
	if "Nymph" in genus:
		descriptor += [
			"Forest", "Graceful",
			"Nature", "Nymph",
			"Water",
			]
	if "Celestial" in genus:
		descriptor += [
			"Divine", "Holy",
			"Celestial",
			"Celestian",
			]
	if "Angel" in genus:
		descriptor += [
			"Angelic",
			"Divine",
			"Holy",

			"Messenger",
			"Seraphic",
			"Winged",
			]
	if "Atlantian" in genus:
		descriptor += [
			"Ancient",
			"Aquatic",
			"Deepsea",

			"Nautic",
			"Ruinbound",
			]
	if "Dragonborn" in genus:
		descriptor += [
			"Tailed", "Blueblood",
			"Dragonborn",
			"Fireblood", "Greenblood",
			"Iceblood",
			"Nightblood",
			]
	if "Noble" in genus:
		descriptor += [
			"Graceful",
			"Influential",
			"Mayor",
			"Noble",
			"Refined",

			"Ruler",
			"Sovereign",
			"Aristocratic",
			"Bountiful",
			]
	if "Hunter" in genus:
		descriptor += [
			"Primal",
			]

	if "Monkey King" in genus:
		descriptor += [
			"Tailed",
			"Cunning",
			"Mammalian",
			"Mighty",
			"Monkey",

			"Tricking",
			"Tricksy",
			"Whimsy",
			"Adventuring",
			]
	if "Birdfolk" in genus:
		descriptor += [
			"Flying",
			"Songbird",
			]
	if "Cleric" in genus:
		descriptor += [
			"Devout",
			"Golden",
			"Holy",

			"Righteous",
			"Spiritual",
			"Blessed",
			]
	if "Beast" in genus:
		descriptor += [
			"Tailed", "Jungle",
			"Sylvan", "Nature",
			"Beast",
			]
	if "Chaotic" in genus:
		descriptor += [
			"Anarchic",
			"Erratic",
			"Mad",

			"Unpredictable",
			"Whimsical",
			"Free",
			]
	if "Dragon" in genus:
		descriptor += [
			"Tailed",
			"Clever",
			"Destroyer",
			"Draconic",
			"Eternal",
			"Evil",
			"Fierce",
			"Fierce",
			"Fire",
			"Flame",
			"Furious",
			"Gentle",
			"Great",
			"Grumpy",
			"Intelligent",
			"Jealous",
			"Jungle",
			"Kind",
			"Magnificent",
			"Magnificent",
			"Majestic",
			"Maximum",
			"Mysterious",
			"Powerful",
			"Scaled",
			"Sky",
			"Strong",
			"Stubborn",
			"Voiceless",
			"Winged",
			"Legendary",
			"Wise",
			"Reptile",
			"Magnanimous",
			]
		if "Chromatic" in genus:
			descriptor += [
				"Chromatic",
				]

		if "Metallic" in genus:
			descriptor += [
				"Metallic",
				]
		if "Prismatic" in genus:
			descriptor += [
				"Prismatic",
				]
		if "Red" in genus:
			descriptor += [
				"Red",
				"Fireborn",
				"Fireblood",
				"Firewing",
				"Fireclaw",
				"Firetail",
				"Firescale",
				"Firewing",

				"Fireclaw",
				"Firetail",
				"Firescale",
				"Crimson",
				"Flameborn",
				"Volcanic",
				"Furious",
				]
		if "Green" in genus:
			descriptor += [
				"Green",
				"Emerald",
				"Acidic",
				]
		if "Blue" in genus:
			descriptor += [
				"Blue",
				"Electric",
				"Desertic",
				]
		if "Black" in genus:
			descriptor += [
				"Black", "Shadow",
				"Necrotic", "Deathly",
				"Haunting", "Dark",
				]
		if "White" in genus:
			descriptor += [
				"White",
				"Ice",
				"Frost",
				"Cold",
				"Winter",
				"Snow",
				"Frozen",
				"Frostborn",
				"Iceborn",
				"Iceblood",
				"Icewing",
				"Iceclaw",
				"Icetail",

				"Icecale",
				"Icewing",
				"Iceclaw",
				"Icetail",
				"Icecale",
				"Frostborn",
				"Iceborn",
				"Iceblood",
				"Icewing",
				"Iceclaw",
				"Icetail",
				"Icecale",
				]
		if "Gold" in genus:
			descriptor += [
				"Gold",
				"Golden",
				"Sun",
				"Sunlight",
				"Sunlit",

				"Sunrise",
				"Sunset",
				"Sunstone",
				"Sunflare",
				]
		if "Silver" in genus:
			descriptor += [
				"Silver",
				"Silver",

				"Moon",
				"Moonlight",
				]
		if "Bronze" in genus:
			descriptor += [
				"Bronze",
				]

	if "Aberration" in genus:
		descriptor += [
			"Alien", "Aberrant",
			"Astral",
			"Eldritch", "Eldritch",
			"Existential",
			"Formless", "Forsaken",
			"Green",
			"Horror", "Identity",
			"Jungle",
			"Lost", "Mind",
			"Nether",
			"Soulless", "Underworld",
			"Unworldly",
			"Yellow",
			]
	if "Beholder" in genus:
		descriptor += [
			"All Seeing", "Beholder", "Omniscient",
			"Paranoid", "Tyrannical",
			"Unblinking", "Visionary",
			]
	if "Old One" in genus:
		descriptor += [
			"Ancient",
			"All Knowing",
			"Eldritch",

			"Mysterious",
			"Old",
			"Timeless",
			]
	if "Mindlinker" in genus:
		descriptor += [
			"Benevolent",
			"Knowledge",
			"Linker",
			"Mind",

			"Seeker",
			"Thought",
			"Weaver",
			"Wise",
			]
	if "Dominators" in genus:
		descriptor += [
			"Commanding",
			"Hierarchical",
			"Ruthless",

			"Subjugating",
			"Tyrant",
			"Master",
			]
	if "Undead" in genus:
		descriptor += [
			"Morgue",
			"Cursed",
			"Urn",
			"Deathly",
			"Dreadhorde",
			"Eternal",
			"Ethereal",

			"Ghostly",
			"Ghoul",
			"Haunting",
			"Spectral",
			"Undead",
			"Zombie",
			"Ancient",
			]
	if "Warlock" in genus:
		descriptor += [
			"Eldritch",
			"Fallen",
			"Mage",
			"Mysterious",
			"New",

			"Otherworldly",
			"Pact",
			"Arcane",
			"Arcane",
			"Tarot",
			]
	if "Illithid" in genus:
		descriptor += [
			"Mind",
			"Psionic",
			"Telepathic",
			"Brain",
			"Thought",
			"Cerebral",
			"Deep",
			"Dimensional",
			"Dream",
			"Eldritch",
			"Illithid",
			"Inscrutable",
			"Insidious",

			"Mindbending",
			"Otherworldly",
			"Psionic",
			"Shadowspeaker",
			"Soul",
			"Telepathic",
			"Thought",
			"Trascendent",
			"Voidborn",
			"Void",
			"Warp",
			"Astral",
			]
	if "Shapeshifters" in genus:
		descriptor += [
			"Amorphous", "Changeling",
			"Formless", "Mimic",
			"Mutant", "Protean",
			]
	if "Living Spell" in genus:
		descriptor += [
			"Arcane",
			"Enchanted",
			"Enchantment",
			"Ethereal",

			"Golden",
			"Green",
			"Magenta",
			"Magic",

			"Magical",
			"Spellbound",
			"Wizardly",
			"Amber",
			]
	if "Dog" in genus:
		descriptor += [
			"Fierce", "Hellhound",
			"Loyal", "Mammal",
			"Three Head",
			]
	if "Warrior" in genus:
		descriptor += [
			"Battle", "Fearless",
			"Honorable", "Mighty",
			"Ready", "Skilled",
			]
	if "Alien Spawn" in genus:
		descriptor += [
			"Alien", "Extraterrestrial",
			"Otherworldly", "Starborne",
			"Unearthly",
			]
	if "Monstrosity" in genus:
		descriptor += [
			"Beastly", "Fearsome",
			"Monstrous", "Mythical",
			"Terrifying", "Yellow",
			]
		if "Sphynx" in genus:
			descriptor += [
				"Thoughtful",
				]
	if "Mage" in genus:
		descriptor += [
			"Arcane",
			"Sorcery",

			"Sorcerous",
			"Portal",
			]
	if "Elf" in genus:
		descriptor += [
			"Elfstone", "Fae",
			]
	if "Fey" in genus:
		descriptor += [
			"Fey", "Fae",
			]
	if "Ghost" in genus:
		descriptor += [
			"Ethereal", "Mournful", "Pain",
			"Sorrow", "Unresolved",
			"Urn", "Unholy",
			]
	if "Catfolk" in genus:
		descriptor += [
			"Agile", "Amber", "Cat", "Claw",
			"Feline", "Mammalian", "Mystical", "Prowler",
			"Shadow", "Stealthy", "Whiskered", "Whiskers",
			]
	if "Centaur" in genus:
		descriptor += [
			"Centaur",
			"Equs",
			"Forest",
			"Horse",

			"Herd",
			"Hooved",
			"Wildheart",
			]
	if "Fiend" in genus:
		descriptor += [
			"Amber", "Caustic", "Contaminated", "Dark", "Demon",
			"Demonic", "Diabolical", "Fiendish", "Hell", "Infernal",
			"Liar", "Malevolent", "Red", "Sinister", "Unholy",
			]
	if "Owl" in genus:
		descriptor += [
			"All Seeing", "Mystic", "Mystical", "Night",
			"Nocturnal", "Omniscient", "Silent",
			"Silentwing", "Wisdom", "Wise",
			]
	if "Kitsune" in genus:
		descriptor += [
			"Nine Tales", "Amber", "Masked", "Astral", "Blue", "Blue", "Cunning",
			"Enchanted", "Enchanter", "Enchanting", "Fox", "Foxfire", "Foxy",
			"Golden", "Illusion", "Illusory", "Mystic", "Mystical", "Nine Tailed", "Nine Tailed",
			"Red", "Tailed", "Tale", "Trickster", "Trickster", "Yellow",
			]
	if "Lion" in genus or "Leon" in genus:
		descriptor += [
			"Amber", "Brave", "Exalted", "Gold", "Golden", "Golden",
			"Lion", "Majestic", "Mammalian", "Pride", "Pride",
			"Regal", "Roaring", "Sun", "Sunlit", "Yellow",
			]
	if "Mage" in genus:
		descriptor += [
			"Arcane", "Arcane", "Black", "Blue", "Crimson", "Enigmatic",
			"Golden", "Green", "Grey", "Learned", "Mystical", "Rainbow",
			"Red", "Scholar", "Sorcerous", "Spellbinder", "White", "Yellow",
			]
	if "Ooze" in genus:
		descriptor += [
			"Absorbing",
			"Absorbing",
			"Acidic",
			"Amorphous",
			"Amorphous",
			"Ashen",
			"Crystalline",
			"Cubic",
			"Earthen",
			"Fiery",
			"Fluidic",
			"Fungal",
			"Gelatinous",
			"Gelatinous",
			"Glowing",

			"Icy",
			"Mystical",
			"Poisonous",
			"Shapeless",
			"Shapeless",
			"Slime",
			"Slithering",
			"Slithering",
			"Sticky",
			"Thick",
			"Translucent",
			"Viscous",
			"Viscous",
			"Viscous",
			]
	if "High" in genus:
		descriptor += [
			"Elevated",
			"High",
			"Refined",
			]
	if "Merchant" in genus:
		descriptor += [
			"Bountiful",
			]
	if "Crafter" in genus:
		descriptor += [
			"Voltaic",
			"Crafty",
			"Urn",
			]
	if "Mountain" in genus:
		descriptor += [
			"Crafty", "Rugged", "Snowy", "Stoic", "Unyielding", "Enduring", "Harsh", "Mountain", "Resilient", "Earthen", "Stone", "Deep", "Rooted", "Gritty", "Metalwork", "Ancestral", "Tough", "Boulder", "Unmovable", "Iron", "Strong", "Mining", "Gem", "Ore", "Frost", "Ale", "Echo", "Gold", "Silver", "Mithril", "Carver",
			]
	if "Sea" in genus:
		descriptor += [
			"Aquatic", "Piscine",
			"Coastal", "Maritime",
			"Oceanic", "Gilled",
			]
	if "Etherian" in genus:
		descriptor += [
			"Voltaic", "Ethereal",
			"Luminous", "Heavenly",
			"Celestial", "Stardust",
			]
	if "Snakefolk" in genus:
		descriptor += [
			"Ophidian",
			]

	if "Good" in genus:
		descriptor += [
			"Celestial",
			"Helping",
			"Benevolent",
			"Kind",
			"Gentle",

			"Gentle",
			"Tender",
			"Hopeful",
			"Jubilant",
			]
	if "Lawful" in genus:
		descriptor += [
			"Hierarchy", "Disciplined",
			]
	if "Chaotic" in genus:
		descriptor += [
			"Untamed",
			"Chaos",
			"Chaos",
			"Anarchy",
			"Free",
			"Chaotic",

			"Unpredictable",
			"Erratic",
			"Anarchic",
			"Anarchist",
			"Freedom",
			]

	if "Evil" in genus:
		descriptor += [
			"Corrupt",
			"Corrupted",
			"Pernicious",
			"Dark",
			"Evil",
			"Malignant",

			"Cruel",
			"Foul",
			"Nefarious",
			"Angry",
			"Jealous",
			"Hostile",
			]
	if "Lawful" in genus:
		if "Good" in genus:
			descriptor += [
				"Holy",
				]

	descriptor += [
		"Storm",
		"Sky",
		"Green",
		"Angelic",
		"Amethyst",
		"Amber",
		"Amber",
		"Hollow",
		"Empty",
		"Arcane",
		"Alchemical",
		"Apothecarian",
		"Arcanic",
		"Magical",
		"Wand",
		"Wizard",
		"Arcane",
		"Alchemical",
		"Arcanic",
		"Magic",
		"Wand",
		"Wizardry",
		"Myrmidon",
		"Mystic",
		"Mystical",
		"Mythical",
		"Lavender",
		"Oceanic",
		"Glacial",
		"Blind",
		"Mad",
		"Gallant",
		"Generous",
		"Kind",
		"Unbreakable",
		"Valiant",
		"Orphean",
		"Abyssal",
		"Daemonian",
		"Hellish",
		"Holy",
		"Crystal",
		"Earth",
		"Omniscient",
		"Magenta",
		"Yellow",
		"Golden",
		"Goldenrod",
		"Ochre",
		"Green",
		"Jade",
		"Olive",
		"Azure",
		"Blue",
		"Cerulean",
		"Indigo",
		"Lavender",
		"Ivory",
		"Graphite",
		"Iridescent",
		"Gold",
		"Golden",
		"Graphite",
		"Onyx",
		"Ivory",
		"Gemmed",
		"Jewel",
		"Jewelcraft",
		"Eternal",
		"Glimmer",
		"Glaive",
		"Gem",
		"Ghost",
		"Gale",
		"Gaze",
		"Jeweled",
		"Northern",
		"Opal",
		"Jade",
		"Quartz",
		"Red",
		"Topaz",
		"Xenolith",
		"Elfstone",
		"Deep",
		"Scrappy",
		"Honor",
		"Mighty",
		"Fearless",
		"Battle",
		"Ghost",
		"Cloud",
		"Dream",
		"Gloom",
		"Golden",
		"Graceful",
		"Green",
		"Grove",
		"Heart",
		"Hell",
		"Hidden",
		"High",
		"Horn",
		"Hydra",
		"Lamp",
		"Last",
		"Leaf",
		"Lore",
		"Lost",
		"Lunar",
		"Magenta",
		"Master",
		"Maze",
		"Mind",
		"Mischief",
		"Mystic",
		"Night",
		"Plains",
		"Planar",
		"Potion",
		"Pride",
		"Proud",
		"Red",
		"Rune",
		"Sacred",
		"Sky",
		"Spell",
		"Star",
		"Silk",
		"Stone",
		"Story",
		"Tunneling",
		"Vine",
		"Yellow",
		"Reptile",
		"Ruby",
		"Turtle",
		"Furious",
		"Ghostly",
		"Hesperidean",
		"Ice",
		"Illustrious",
		"Imaginative",
		"Inscrutable",
		"Interstellar",
		"Lagoon",
		"Leviathan",
		"Liquid",
		"Lord",
		"Lunar",
		"Majestic",
		"Malign",
		"Martial",
		"Merry",
		"Meteor",
		"Meteoric",
		"Mighty",
		"Mirthful",
		"Monstrous",
		"Moonlit",
		"Mystical",
		"Occult",
		"Oracle",
		"Oracular",
		"Ordinance",
		"Pathfinder",
		"Peerless",
		"Perennial",
		"Perfumed",
		"Perilous",
		"Petrified",
		"Phantom",
		"Pillar",
		"Piqued",
		"Planetary",
		"Plum",
		"Poetic",
		"Polar",
		"Precocious",
		"Predatory",
		"Profound",
		"Promethean",
		"Protector",
		"Psychic",
		]

	return lusor.Pick(
		descriptor,
		dice=dice,
		)
