'''
Origins: the provenance of a title, the X of "The Dark Lord of X".

A vocabulary of Map_of_Titles: a word list keyed by what the lusor's genus
answers. The story engine (Map_of_Stories) may import it directly, without
the title composer.

The origin draws on every other vocabulary, so this file imports them by
their files; nothing here imports the package.
'''
from .descriptors import Descriptor
from .ranks import Rank
from .places import Place
from .artifacts import Artifact
from .elements import Element
from .masters import Master
from .animals import Animal

def Origin(
		lusor,
		*,
		dice=None,
		):
	'''
If you can say: The Dark Lord of X
X goes here
'''
	try:
		genus = lusor.genus
	except:
		genus = lusor

	descriptor = Descriptor(
		lusor,
		dice=dice,
		)
	rank = Rank(
		lusor,
		dice=dice,
		)

	place = Place(
		lusor,
		dice=dice,
		)

	artifact = Artifact(
		lusor,
		dice=dice,
		)
	element = Element(
		lusor,
		dice=dice,
		)
	master = Master(
		lusor,
		dice=dice,
		)
	animal = Animal(
		lusor,
		dice=dice,
		)

	origin = []

	origin += [
		f"of the {artifact}",
		f"of the {animal}",
		f"of {element}",
		f"of the {element}",
		f"of the {element} {place}",
		f"of the {element} {master}",
		f"of the Mark of {element}",
		f"of the Mark of the {master}",
		f"of the {place} {master}",
		f"of the {place} {artifact}",
		f"of the {descriptor} {artifact}",
		f"of the {descriptor} {place}",
		f"of the {descriptor} Sanctuary",
		f"of the {descriptor} Dungeon",
		f"of the {descriptor} Woods",
		f"of the {descriptor} Forest",
		f"of the {descriptor} Tomb",
		f"of the {descriptor} Lands",
		f"of the {descriptor} Caves",
		f"of the {descriptor} Halls",
		f"of the {descriptor} Temple",
		f"of the {descriptor} Temples",
		f"of the {descriptor} Ruins",
		f"of the {descriptor} Wilds",
		f"of the {descriptor} Abyss",
		f"of the {descriptor} Desert",
		f"of the {descriptor} Lake",
		f"of the {descriptor} Sea",
		f"of the {descriptor} Ocean",

		f"of the {descriptor} Labyrinth",
		f"of the {descriptor} Labyrinths",
		f"of the {descriptor} Road",
		f"of the {descriptor} Paths",
		f"of the {descriptor} Circle",
		f"of the {descriptor} Skies",
		f"of the {descriptor} Court",

		f"of the {descriptor} Throne",
		f"of the {descriptor} Watch",
		f"of the {descriptor} Fortress",
		f"of the {descriptor} Marshes",
		f"of the {descriptor} Camp",
		f"of the {descriptor} Garden",
		f"of the {descriptor} Gardens",
		f"of the {descriptor} Peaks",
		f"of the {descriptor} Forest",
		f"of the {descriptor} Forests",
		f"of the {descriptor} Lands",
		f"of the {descriptor} Caves",
		f"of the {descriptor} Halls",
		f"of the {descriptor} Temples",
		f"of the {descriptor} Groves",
		f"of the {descriptor} Grove",
		f"of the {descriptor} Wastes",
		f"of the {descriptor} Aura",
		f"of the {descriptor} Dragon",
		f"of the {descriptor} Dungeon",
		f"of the {descriptor} Fire",
		f"of the {descriptor} Kingdom",
		f"of the {descriptor} Realm",
		f"of the {descriptor} Sanctuary",
		f"of the {descriptor} Shadows",
		"of the Pegasus",
		"with no master",
		"with no masters",
		"of Progress",
		"of the Fallen",
		"of the Shrine",
		"of the Godless Shrine",
		f"of the {descriptor} Shrine",
		"of Zenithar",
		"of Kazandu",
		f"of the {descriptor} Tomb",
		"of Time",
		"of the Fires",
		"of the Fires",
		"of Hell",
		"of the Fateweb",
		"of the Golden Sun",
		f"of the {descriptor} Sun",
		"of the First Sun",
		"of the Dark Sun",
		"of the Red Sun",
		"of the White Sun",
		"of the Black Sun",
		"of the Antisun",

		"of The Amulet",
		"of The Sword",
		"of The Talisman",
		"of The Goblet",
		"of the Galaxy",

		"of Baba Yaga",
		"of the Kraken",
		"of the Hydra",
		"of the Waterfall",
		f"of the {descriptor} Waterfall",
		f"of the {descriptor} Sagas",
		f"of the {descriptor} Eternals",
		"of the Eternal Sagas",
		"of the Eternals",
		"Of Athena",
		"of Delphos",
		"of the Underworld Gate",
		"of the Underworld",
		"Odyssey",
		"Of Death",
		"of El Dorado",
		"of Eldorado",
		"Of Fate",
		"Of Heaven",
		"Of Justice",
		"Of Odin",
		"Of The Abyss",
		"Of the Autumn",
		"Of The Crown",
		"Of The Dead",
		"Of The Desert",
		"Of the Divine",
		"Of The East",
		"Of The Fiends",
		"Of The Forest",
		"Of The Forge",
		"Of The Hells",
		"Of The Hills",
		"Of the Hidden",
		"Of the Kingdom",
		"Of the Last Fire",
		"Of The Mountain",
		"Of The North",
		"Of the Oceans",
		"Of the Old One",
		"Of The Oracle",
		"Of the Pack",
		"Of The People",
		"Of The Pharaoh",
		"Of The Plains",
		"Of The Sands",
		"Of The Sea",
		"Of The South",
		"Of The Spring",
		"Of The Storm",
		"Of The Summer",
		"Of The West",
		"Of The Winter",
		"Of Thor",
		"Of Youth",
		"Of Zeus",
		"of the Faith",
		"of the Forty Thieves",
		"of the Morningstar",
		"of the Thousand Tears",
		"of the Jungle",
		"of the City",
		"of the Land",
		"of the North",
		"of the South",
		"of the East",
		"of the West",
		"of the Forest",
		"of the Plains",
		"of the Sea",
		"of the Sky",
		"of Fire",
		"of the Jewels", "of the Ruby",
		"of Gold",
		"of Silver",
		"of Iron",
		"of Steel",
		f"of the {descriptor} Woods",
		f"of the {descriptor} Woods",
		f"of the {descriptor} Woods",
		f"of the {descriptor} Woods",
		f"of the {descriptor} Woods",
		f"of the {descriptor} Woods",
		f"of the {descriptor} Woods",
		f"of the {descriptor} Woods",
		f"of the {descriptor} Woods",
		f"of the {descriptor} Woods",
		f"of the {descriptor} Woods",
		f"of the {descriptor} Woods",
		f"of the {descriptor} Woods",
		f"of the {descriptor} Woods",
		f"of the {descriptor} Woods",
		f"of the {descriptor} Woods",
		f"of the {descriptor} Woods",
		f"of the {descriptor} Woods",
		f"of the {descriptor} Realms",
		f"of the {descriptor} Realms",
		f"of the {descriptor} Realms",
		f"of the {descriptor} Realms",
		f"of the {descriptor} Realms",
		f"of the {descriptor} Realms",
		f"of the {descriptor} Realms",
		f"of the {descriptor} Realms",
		f"of the {descriptor} Realms",
		f"of the {descriptor} Realms",
		f"of the {descriptor} Realms",
		f"of the {descriptor} Realms",
		f"of the {descriptor} Realms",
		f"of the {descriptor} Realms",
		f"of the {descriptor} Realms",
		f"of the {descriptor} Realms",
		f"of the {descriptor} Realms",
		f"of the {descriptor} Realms",
		f"of the {descriptor} Realms",
		f"of the {descriptor} Realms",
		f"of the {descriptor} Realms",
		f"of the {descriptor} Realms",
		f"of the {descriptor} Realms",
		f"of the {descriptor} Realms",
		"of Hamlet",
		"of the Swamp",
		"of the Island",
		"of the Forest",
		"of the Plain",
		"of the Mountain",
		"of the Swamps",
		"of the Islands",
		"of the Forests",
		"of the Plains",
		"of the Mountains",
		"of the Cosmos",
		"of Dread",
		f"of the {rank}'s Curse",
		f"of the {descriptor} Curse",
		"of the Curse",
		"of the Crypt",
		f"of the {descriptor} Crypt",
		f"of the {descriptor} City",
		"of the Golden City",
		"of the Ouroboros",
		f"of the {descriptor} Master",

		f"of the {descriptor} Wars",
		f"of the {descriptor} War",
		f"of the {rank} Wars",
		f"of the {rank} War",

		"of the Wars",
		"of the War",
		"of the Damned",
		"of the Moon",
		"from the Moon",
		"of the Jungle",
		"from the Jungle",
		f"of the {descriptor} Shadows",
		"of Orisha",
		"of Osiris",
		"of Jade",
		"of Justice",
		"of Beauty",
		"of Ambition",
		"of the Parliament",
		"of Appetite",
		"of Change",
		"of Endeavor",
		"of Adventure",
		f"from the {descriptor} Island",
		f"of the {descriptor} Island",
		"from the Island",
		"of the Island",
		"of the Hive",
		"of the Hill",
		"from the Hill",
		"of the Heath",
		"of the Harbor",
		"of the Hamlet",
		"of the Geyser",
		"of the Garden",
		"of the Gulf",
		"of Merlin",
		"of the Griffon",
		"of Cthulhu",
		"of the Jackal",
		"of the Banshee",
		"of Pirates",
		"of Odin",
		"from the Hill",
		"of the Nymph",
		"from Nature",
		"of the Wizards",
		"of Nature",
		"of Light",
		"of Nature",
		"from Nature",
		"of Adventures",
		"of Nature",
		"of the Circle",
		"of Zombies",
		"of Warriors",
		"of Warlords",
		"of Vecna",
		"of Werewolves",
		"of the Valkyrie",
		"of the Universe",
		"of Trolls",
		"of the Sorcerer",
		"of the Totem",
		"of the Shepherd",
		"of the Shaman",
		"of Shamans",
		f"of the {descriptor} Shaman",
		"of the Serpent",
		f"of the {descriptor} Serpent",
		"of Serpents",
		"of Terrible Secrets",
		f"of the {descriptor} Scholar",
		f"of the {descriptor} River",
		"of the River",
		"of the Queen",
		f"of the {descriptor} Queen",
		"of the Prince",
		f"of the {descriptor} Prince",
		"of the Pirate",
		"of Pirates",
		f"of the {descriptor} Pirates",
		"of the Minotaur",
		"of the Oracle",
		"of Odin",
		f"of the {descriptor} Meadow",
		"of the Meadow",
		f"of the {descriptor} Mage",
		"of the Mage",
		"of Mages",
		"of the Master",
		f"of the {descriptor} Master",
		f"of the {descriptor} Lich",
		"of the Lich",
		f"of the {descriptor} Lion",
		"of the Lion",
		"from the Labyrinth",
		f"of the {descriptor} Labyrinth",
		"of the Labyrinth",
		f"of the {descriptor} Kraken",
		"of the Kraken",
		f"of the {rank} Knight",
		f"of the {descriptor} Knight",
		"of the Knight",
		f"of the {descriptor} Kingdom",
		f"of the {rank} Kingdom",
		"of the Kingdom",
		"of the King",
		f"of the {descriptor} King",
		f"of the {rank} King",
		"of the Inn",
		f"of the {rank} Inn",
		f"of the {descriptor} Inn",
		"of the Highlord",
		f"of the {descriptor} Highlord",
		"of the Harbor",
		f"of {rank} Harbor",
		f"of {descriptor} Harbor",
		"of the Glade",
		f"of the {rank} Glade",
		f"of the {descriptor} Glade",
		"of the Gulf",
		f"of the {rank} Gulf",
		f"of the {descriptor} Gulf",
		"of the Guild",
		f"of the {rank} Guild",
		f"of the {descriptor} Guild",
		"of the Guardian",
		f"of the {rank} Guardian",
		f"of the {descriptor} Guardian",
		f"of the {descriptor} Geyser",
		"of the Geyser",
		f"of the {descriptor} Field",
		"of the Field",
		"of the Eagle",
		"of the Elixir",
		f"of the {descriptor} Elixir",
		"of Death",
		f"of the {descriptor} Death",
		"of the Crown",
		"of the Condor",
		"of the Boar",
		f"of {descriptor} Battle",
		f"of {rank} Battle",
		"of Battle",
		f"of the {descriptor} Battle",
		f"of the {rank} Battle",
		"of the Battle",
		"of the Baobab",
		"of the Baron",
		"of the Amulet",
		"of the Amazon",
		"of the Arena",
		"of War",
		"of Wizards",
		"of the Wolf",
		f"of the {descriptor} Wolf",
		f"of the {descriptor} Wizard",
		"of the Skies",
		"from Beyond the Veil",
		"from Beyond The Wall",
		"of Stonehenge",
		"of the Cemetery",
		"of the Temple",
		"of Malady",
		"of the Paladin",
		"of the Pyramid",
		f"of the {descriptor} Pyramid",
		"of the Labyrinth",
		f"of the {descriptor} Labyrinth",
		f"of the {descriptor} Laboratory",
		"of the Laboratory",
		"of the Wilderness",
		f"of the {descriptor} Hunter",
		"of the Hunter",
		"of the Kraken",
		f"of the {rank} Organization",
		f"of the {descriptor} Organization",
		f"of the {rank} Organization",
		f"of the {descriptor} Organization",
		f"of the {rank} Organization",
		f"of the {descriptor} Organization",
		f"of the {rank} Organization",
		f"of the {descriptor} Organization",
		"of the Organization",
		f"of the {rank} Guild",
		f"of the {rank} Guild",
		f"of the {rank} Guild",
		f"of the {rank} Guild",
		f"of the {rank} Guild",
		f"of the {rank} Guild",
		f"of the {rank} Guild",
		f"of the {descriptor} Guild",
		"of the Guild",
		"of the Werewolves",
		"of the Galaxy",
		"of the Sphinx",
		"of Infinity",
		"of the Grassland",
		f"of the {descriptor} Grassland",
		"of Mystery",
		"of Mischief",
		"of Secrecy",
		"of the Kingdom",
		f"of the {descriptor} Kingdom",
		f"of the {descriptor} Baron",
		"of the Baron",
		"of Condor",
		"of the Hive",
		f"of the {descriptor} Wolf",
		"of the Wolf",
		"of The Goblet",
		"of The Talisman",
		"of The Sword",
		"of The Amulet",
		f"of The {descriptor} Goblet",
		f"of The {descriptor} Talisman",
		f"of The {descriptor} Sword",
		f"of The {descriptor} Amulet",
		f"of the {descriptor} Waterfall",
		"of the Waterfall",
		"of the Order",
		f"of the {descriptor} Order",
		"of the Owl",
		"of the Garden",
		"of the Ghost",
		f"of the {descriptor} Ghost",
		f"of {descriptor} Ghosts",
		"of Ghosts",
		f"of the {descriptor} Garden",
		"Of Athena",
		"of Delphos",
		"of the Vampire",
		"of the Underworld Gate",
		"of the Underworld",
		"of the Odyssey",
		"of Death",
		"of El Dorado",
		"of Eldorado",
		"of Fate",
		"Of Heaven", "Of Justice",
		"Of Odin",
		"Of The Abyss",
		"Of the Autumn",

		"Of Justice",
		"Of Odin",
		"Of The Abyss",
		"Of the Autumn",

		"Of The Crown",
		"Of The Dead",
		"Of The Desert",
		"Of the Divine",
		"Of The East",
		"Of The Fiends",
		"Of The Forest",
		"Of The Forge",
		"Of The Hells",
		"Of The Hills",
		"Of the Hidden",
		"of the Kingdom",
		"Of the Last Fire",
		"Of The Mountain",
		"Of The North",
		"Of the Oceans",
		"Of the Old One",
		"Of The Oracle",
		"Of the Pack",
		"Of The People",
		"Of The Pharaoh",
		"Of The Plains",
		"Of The Sands",
		"Of The Sea",
		"Of The South",
		"Of The Spring",
		"Of The Storm",
		"Of The Summer",
		"Of The West",
		"Of The Winter",
		"Of Thor",
		"Of Youth",
		"Of Zeus",
		"of the Faith",
		"of the Forty Thieves",
		"of the Morningstar",
		"of the Thousand Tears",
		"of the Jungle",
		"of the City",
		"of the Land",
		"of the North",
		"of the South",
		"of the East",
		"of the West",
		"of the Forest",
		"of the Plains",
		"of the Sea",
		"of the Sky",
		"of Fire",
		f"of the {descriptor} Tactics",
		f"of the {descriptor} City",
		"of the Golden City",
		"of the Treasure", "of the Kraken",
		"of the Sunlord",
		"of Sundiata",

		"of the Sword",
		"of Baba Yaga",
		f"of the {descriptor} Kraken",
		"of the Hydra",
		"of the Aegean",
		"of the Amazon",
		"of the Amazonians",
		"of the Archipelago",
		f"of the {descriptor} Archipelago",
		"of the Asgardians",
		"of the Atlanteans",
		"of the Aztecs", "of the Badlands",
		"of the Babylonians", "of the Bay",
		f"of the {descriptor} Bay",
		"of the Beach",
		f"of the {descriptor} Beach",
		"of the Glade",
		f"of the {descriptor} Glade",
		"of the Gorgonians",
		"of the Grassland",
		f"of the {descriptor} Grassland",
		"of the Gulf",
		f"of the {descriptor} Gulf",
		"of the Garden",
		f"of the {descriptor} Garden",
		"of the Geyser",
		f"of the {descriptor} Geyser",
		"of the Harbor",
		f"of the {descriptor} Harbor",
		f"of {descriptor} Harbor",
		"of the Hill",
		f"of the {descriptor} Hill",
		"of the Island",
		f"of the {descriptor} Island",
		f"of {descriptor} Island",
		"of the Marsh",
		f"of the {descriptor} Marsh",
		f"of {descriptor} Marsh",
		"of the Meadow",
		f"of the {descriptor} Meadow",
		f"of {descriptor} Meadows",
		"of the Mine",
		f"of the {descriptor} Mine",
		f"of {descriptor}mine",
		"of Moss",
		"of the Mountain",
		f"of the {descriptor} Mountain",
		f"of {descriptor} Mountain",
		"of the Museum",
		f"of the {descriptor} Museum",
		"of the Oasis",
		f"of the {descriptor} Oasis",
		f"of {descriptor} Oasis",
		"of the Ocean",
		f"of {descriptor} Ocean",
		f"of the {descriptor} Ocean",
		"of the Outpost",
		f"of the {descriptor} Outpost",
		f"of {descriptor} Outpost",
		"of the Outlands",
		f"of the {descriptor} Outlands",
		f"of {descriptor} Outlands",
		"of the Glade",
		f"of the {descriptor} Glade",
		f"of {descriptor} Glade",
		"of the Grassland",
		f"of the {descriptor} Grassland",
		"of the Graveyard",
		f"of the {descriptor} Graveyard",
		"of the Grove",
		f"of the {descriptor} Grove",
		f"of the {descriptor} Abyss",
		"of The Seventh Hell",
		"of Hell",
		"of the Hells",
		f"of the {descriptor} Hells",
		"of Horus",
		"of the Jewels",
		"of the Ruby",
		"of Gold",
		"of Silver",
		"of Iron",
		"of Steel",
		"of the Underworld",
		f"of the {descriptor} Sanctum",
		f"of the {descriptor} Palace",
		f"of the {rank} Palace",
		"of Osiris",
		"of Helios",
		"of Helio",
		"of Helion",
		"of Heliod",
		"of Blood",
		f"of the {rank} Shrine",
		"of Akros",
		"for the Hunt",
		"of Kiranta",
		f"for the {descriptor} Hunt",
		"of Lunden",
		"of Ages",
		"of the Ages",
		"of Londinium",
		"of the Great Hunt",
		"of Azurius",
		"of Power",
		"of Darkwood",
		"of the Blood Rites",
		f"of the {descriptor} Rites",
		f"of the {rank}'s Island",
		f"of the {descriptor} Island",
		f"of the {descriptor} Hunt",
		"of the Moon Fortress",
		f"of the {descriptor} Fortress",
		f"of the {descriptor} Throne",
		"of the Throne",
		"of Queen Boudica",
		"of Liliana",
		"of Athens",
		"of Paradise",
		"of Vesuvius",
		"of Vesuvia",
		"of the Glade",
		"of Carcosa",
		"of Azorius",
		"of Nylea",
		"of Rakdos",
		"of the Monolith",
		"of the Smoke",
		"of The Capital",
		"of the Triumvirate",
		f"of the {descriptor} Triumvirate",
		f"of The {descriptor} Smoke",
		f"of The {descriptor} Capital",
		"of the Overgrown Forest",
		"of the Overgrown Land",
		f"of the {descriptor} Monolith",
		"of the Wild Hunt",
		f"of the {descriptor} Hunt",
		f"of the {rank}'s Hunt",
		"of the Ancient Tomb",
		"of the Broken Land",
		"of the Sea Gate",
		"of the Deep",
		f"of the {rank}'s Revenge",
		f"of the {rank}'s Menace",
		"of the Raging Storm",
		f"of the {descriptor} Storm",
		f"of the {descriptor} Fountain",
		f"of the {descriptor} Gate",
		f"of the {descriptor} Land",
		f"of the {descriptor} Tomb",
		f"of the {descriptor} Forest",
		f"of the {rank}'s Palace",
		f"of the {rank}'s Glade",
		f"of the {rank}'s Gate",
		f"of the {rank}'s Land",
		f"of the {rank}'s Forest",
		f"of the {rank}'s Tomb",
		"of the Blossoming Sands",
		f"of the {rank}",
		f"of the {rank}",
		f"of the {rank}",
		f"of the {rank}",
		f"of the {rank}'s Road'",
		f"of the {rank}'s Road'",
		f"of the {rank}'s Road'",
		f"of the {rank}'s Road'",
		"of the Pilgrim's Road",
		"of Myth",
		"Of The Marsh",
		"of the Talisman",
		"of Memory",
		"of the Tiger",
		"of Tigers",
		"of Extinction",
		f"of the {descriptor} Sandbar",
		f"of the {descriptor} Sun's Zenith",
		f"of {descriptor} Memory",
		"of the Watcher",
		"of the Consulate",
		"of the False God",
		f"of the {descriptor} God",
		"of Spirits",
		"of the Moon",
		"Of Mirrodin",
		"of the Depths",
		"of Might",
		"of the Provinces",
		"of the Stars",
		f"of the {descriptor} Star",
		f"of {descriptor} Might",
		"of the Elemental",
		f"of the {descriptor} Elemental",
		"Of Denial",
		"of the Sun",
		"of the Black Sun",
		f"of the {descriptor} Sun",
		"of the Spirit",
		"of the Spirits",
		f"of the {descriptor} Spirit",
		f"of the {descriptor} Spirits",
		"of the Damned",
		"of the Sands of Time",
		f"of the {descriptor} Fire",
		f"of {descriptor} Fire",
		"of the Temple",
		f"of the {descriptor} Temple",
		f"of the {descriptor} Temple",
		"of Death",
		f"of the {rank}'s' Temple",
		"of Fire",
		"of the Flames",
		f"of the {descriptor} Flames",
		f"of the {descriptor} Descent",
		f"of the {descriptor} Destiny",
		f"of the {descriptor} Fire",
		f"of the {descriptor} Heritage",
		f"of the {descriptor} Hoard",
		f"of the {descriptor} Horn",
		f"of the {descriptor} Lineage",
		f"of the {descriptor} Maze",
		f"of the {descriptor} Ocean",
		f"of the {descriptor} Sea",
		f"of the {descriptor} Shore",
		"Of Death",
		"of the Enigma",
		"of the Eclipse",
		"Of Blood",
		"of the Blood Court",
		"of the Throne",
		"of the Tomb",
		"of the Underworld",
		"of the Cavern",
		f"of {descriptor} Duty",
		f"of the {descriptor} Tribe",
		f"of the {descriptor} Wings",
		f"of the {descriptor} Tomb",
		f"of the {descriptor} Throne",
		f"of the {descriptor} Legion",
		f"of the {descriptor} Realm",
		f"of the {descriptor} Court",
		f"of the {descriptor} Blood",
		f"of the {descriptor} Castle",
		f"of the {descriptor} Jungle",
		"of Darkness",
		"of the Covenant",
		f"of the {descriptor} Covenant",
		f"of the {descriptor} Depths",
		"of the Depths",
		"of the Unknown",
		f"of the {descriptor} Unknown",
		"of the Dragon",
		f"of the {descriptor} Prophecy",
		"of the Blood Moon",
		f"of the {descriptor} Moon",
		f"of the {descriptor} Prophecy",
		"of the Plains",
		"of the Hunt",
		"of the Stars",
		f"of the {descriptor} Dream",
		"of the Spirits",
		f"of the {descriptor} Spirit",
		f"of the {descriptor} Mountain",
		f"of the {descriptor} Lair",
		"Of Heaven",
		"Of Justice",
		f"of the {descriptor} Death",
		"Of Odin",
		"Of Power",
		"Of The Abyss",
		"Of the Autumn",
		"Of The Crown",
		"Of The Desert",
		"Of The Dead",
		"Of The East",
		"Of The Forest",
		"Of The Forge",
		"Of The Fiends",
		"Of the Kingdom",
		"Of The Hills",
		"Of the Hells",
		"Of The North",
		"Of The Mountain",
		"Of the Oceans",
		"Of the Old One",
		"Of The Plains",
		"Of the Pack",
		"Of The People",
		"Of The Pharaoh",
		"Of The Sands",
		"Of The Sea",
		"Of The South",
		"Of The Summer",
		"Of The Spring",
		"Of The Storm",
		"Of The West",
		"Of The Winter",
		"Of Thor",
		"Of Zeus",
		"Of Justice",
		"Of The East",
		"Of The West",
		"Of The North",
		"Of The South",
		"Of The Forest",
		"Of The Hills",
		"Of The Mountain",
		"Of The Sands",
		"Of The Sea",
		"of the Wild",
		"of the Otherworld",
		"of Pain",
		f"of the {descriptor} Maelstrom",
		f"of the {descriptor} Whirl",
		f"of the {descriptor} Realm",
		f"of the {descriptor} Vision",
		f"of the {descriptor} Depth",
		f"of the {descriptor} Sands",
		f"of the {descriptor} Storm",
		f"of the {descriptor} Frontier",
		f"of the {descriptor} Battle",
		f"of the {descriptor} Roar",
		f"of the {descriptor} Forest",
		f"of the {descriptor} Meadow",
		f"of the {descriptor} Glades",
		f"of the {descriptor} Forest",
		f"of the {descriptor} Realm",
		f"of the {descriptor} Legend",
		f"of the {descriptor} Wild",
		f"of the {descriptor} Tundra",
		f"of the {descriptor} Pack",
		f"of the {descriptor} Roar",
		f"of the {descriptor} Grove",
		f"of the {descriptor} Sea",
		f"of the {descriptor} Depths",
		"of the Void",
		"of the Stars",
		f"of the {descriptor} World",
		f"of the {descriptor} Ruin",
		f"of the {descriptor} Jungle",
		f"of the {descriptor} Land",
		"of the Endless Hunt",
		f"of the {descriptor} Hunt",
		]

	if "Berserker" in genus:
		origin += [
			f"of the {descriptor} Fury",
			f"of the {descriptor} Tribe",
			f"of the {descriptor} Lands",
			f"of the {descriptor} Mountain",
			f"of the {descriptor} Clan",
			f"of the {descriptor} Raid",
			"of the Colosseum",
			]
	if "Bard" in genus:
		origin += [
			"of the Festival",
			]
	if "Barbarian" in genus:
		origin += [
			f"of the {descriptor} Tribe",
			"Of the Colosseum",
			]
	if "Cleric" in genus:
		origin += [
			"of Rebirth",
			"from Heaven",
			f"from the {descriptor} Heaven",
			f"of the {descriptor} Gods",
			"of the Gods",
			"of the Holy Order",
			"of the Order",
			"of the Mission",
			"of the Journey",
			"of the Path",
			"of the Light",
			f"of the {descriptor} Order",
			f"of the {descriptor} Order",
			f"of the {descriptor} Mission",
			f"of the {descriptor} Journey",
			f"of the {descriptor} Pilgrimage",
			f"of the {descriptor} Crusade",
			f"of the {descriptor} Path",
			f"of the {descriptor} Light",
			f"of the {descriptor} Quest",
			]
	if "Criminal" in genus:
		origin += [
			f"of the {descriptor} Penitentiary",
			"of the Penitentiary",
			"of the Underworld",
			"of the Network",
			f"of the {descriptor} Escape",
			f"of the {descriptor} Ambitions",
			f"of the {descriptor} Deal",
			f"of the {descriptor} Scheme",
			"Of the Colosseum",
			]
	if "Cultist" in genus:
		origin += [
			"of the Abhorrent",
			"from Heaven",
			f"from the {descriptor} Heaven",
			f"of the {descriptor} Gods",
			"of the Gods",
			"of the Sect",
			"of Rites",
			"of the Order",
			"of the Ritual",
			"of the Yellow King",
			"of the King in Yellow",
			f"of the {descriptor} King",
			]
	if "Expert" in genus:
		origin += [
			"of the Scholar",
			"of Scholars",
			"of the Scholar",
			"of the Scholars",
			f"of {descriptor} Field",
			f"of {descriptor} Trade",
			f"of {descriptor} Study",
			f"of {descriptor} Research",
			f"of {descriptor} Skill",
			]
	if "Explorer" in genus:
		origin += [
			"of the Uncharted Lands",
			"of the Jungle",
			f"of the {descriptor} Jungle",
			f"of the {descriptor} Expedition",
			f"of the {descriptor} Journey",
			f"of the {descriptor} Quest",
			f"of the {descriptor} Frontiers",
			]
	if "Crafter" in genus:
		origin += [
			f"of the {descriptor} Hand",
			f"of the {descriptor} Market",
			f"of the {descriptor} Design",
			f"of the {descriptor} Creation",
			f"of the {descriptor} Mind",
			]
	if "Druid" in genus:
		origin += [
			"of the Wild",
			"of the Jungle",
			"of the Woods",
			"of the Grove",
			f"of the {descriptor} Circle",
			f"of the {descriptor} Circle",
			f"of the {descriptor} Circle",
			f"of the {descriptor} Circle",
			f"of the {descriptor} Circle",
			f"of the {descriptor} Circle",
			f"of the {descriptor} Circle",
			f"of the {descriptor} Circle",
			f"of the {descriptor} Circle",
			f"of the {descriptor} Circle",
			f"of the {descriptor} Woods",
			f"of the {descriptor} Woods",
			f"of the {descriptor} Woods",
			f"of the {descriptor} Jungle",
			f"of the {descriptor} Jungle",
			f"of the {descriptor} Jungle",
			f"of the {descriptor} Jungle",
			]
	if "Guard" in genus:
		origin += [
			f"of the {descriptor} Guards",
			f"of the {rank} Guards",
			f"of the {descriptor} Watch",
			f"of the {descriptor} Fortress",
			f"of the {descriptor} Wall",
			f"of the {descriptor} Gate",
			f"of the {descriptor} Patrol",
			f"of the {descriptor} Tower",
			f"of the {descriptor} Keep",
			]
	if "Healer" in genus:
		origin += [
			"from Heaven",
			f"from the {descriptor} Heaven",
			f"of the {descriptor} Gods",
			f"of the {descriptor} Touch",
			f"of the {descriptor} Remedy",
			f"of the {descriptor} Hand",
			f"of the {descriptor} Treatment",
			f"of the {descriptor} Care",
			]
	if "Hero" in genus:
		origin += [
			"from Heaven",
			f"from the {descriptor} Heaven",
			f"of the {descriptor} Gods",
			f"of the {descriptor} Deed",
			f"of the {descriptor} Battle",
			f"of the {descriptor} Venture",
			f"of the {descriptor} Quest",
			f"of the {descriptor} Cause",
			"of the Colosseum",
			f"Of the {descriptor} Colosseum",
			]
	if "Hunter" in genus:
		origin += [
			f"of the {descriptor} Jungle",
			f"of the {descriptor} Hunt",
			f"of the {descriptor} Stealth",
			f"of the {descriptor} Wilderness",
			f"of the {descriptor} Range",
			f"of the {descriptor} Snares",
			"of the Wild Hunt",
			f"of the {descriptor} Hunt",
			]
	if "Knight" in genus:
		origin += [
			f"of the {descriptor} Gods",
			f"of the {descriptor} Order",
			f"of the {descriptor} Quest",
			f"of the {descriptor} Deed",
			f"of the {descriptor} Battle",
			f"of the {descriptor} Venture",
			]
	if "Mage" in genus:
		origin += [
			"of Mysteries",
			"of Mystical Arts",
			"of the Scrolls",
			"of Potions",
			f"of the {descriptor} Academy",
			f"of the {descriptor} Tower",
			f"of the {descriptor} Scroll",
			f"of the {descriptor} Mystery",
			]
	if "Monk" in genus:
		origin += [
			"from Heaven",
			f"from the {descriptor} Heaven",
			f"of the {descriptor} Gods",
			f"of the {descriptor} Path",
			f"of {descriptor} Enlightenment",
			f"of {descriptor} Tranquility",
			f"of the {descriptor} Way",
			f"of {descriptor} Balance",
			f"of {descriptor} Order",
			]
	if "Merchant" in genus:
		origin += [
			f"of the {descriptor} Empire",
			f"of the {descriptor} Market",
			f"of the {descriptor} Venture",
			f"of the {descriptor} Organization",
			f"of the {descriptor} Company",
			f"of the {descriptor} Company",
			f"of the {descriptor} Company",
			f"of the {descriptor} Company",
			f"of the {descriptor} Corporation",
			f"of the {descriptor} Corporation",
			f"of the {descriptor} Corporation",
			f"of the {descriptor} Corporation",
			f"of the {descriptor} Corporation",
			]
	if "Pirate" in genus:
		origin += [
			"of Blackbeard",
			f"of the {descriptor}beard",
			f"of the {descriptor} Sea",
			f"of the {descriptor} Crew",
			f"of the {descriptor} Voyage",
			f"of the {descriptor} Journey",
			f"of the {descriptor} Fleet",
			f"of the {descriptor} Ship",
			f"of the {descriptor} Treasure",
			]
	if "Ranger" in genus:
		origin += [
			f"of the {descriptor} Jungle",
			f"of the {descriptor} Paths",
			f"of the {descriptor} Hunts",
			f"of the {descriptor} Camps",
			f"of the {descriptor} Mountains",
			f"of the {descriptor} Secrets",
			]
	if "Scholar" in genus:
		origin += [
			"of the Scholar",
			"of Scholars",
			"of the Scholar",
			"of the Scholars",
			f"of {descriptor} Scholar",
			f"of {descriptor} Scholars",
			f"of the {descriptor} Scholar",
			f"of the {descriptor} Scholars",
			f"of the {descriptor} Academy",
			f"of the {descriptor} Society",
			f"of the {descriptor} Library",
			f"of the {descriptor} Lecture",
			f"of the {descriptor} Scroll",
			]
	if "Soldier" in genus:
		origin += [
			f"of the {descriptor} Regiments",
			f"of the {descriptor} Regiment",
			f"of the {descriptor} Regiment",
			f"of the {descriptor} Fronts",
			f"of the {descriptor} Fronts",
			f"of the {descriptor} Commands",
			f"of the {descriptor} Units",
			f"of the {descriptor} Operations",
			f"of {descriptor} Operations",
			"of the Colosseum",
			f"of the {descriptor} Colosseum",
			]
	if "Wizard" in genus:
		origin += [
			"of the Scholar",
			"of Scholars",
			"of the Scholar",
			"of the Scholars",
			f"of {descriptor} Scholar",
			f"of {descriptor} Scholars",
			f"of the {descriptor} Scholar",
			f"of the {descriptor} Scholars",
			"of Merlin",
			]
	if "Sorcerer" in genus:
		origin += [
			f"of {descriptor} Ancestry",
			f"of {descriptor} Descent",
			f"of {descriptor} Genealogy",
			f"of {descriptor} Origin",
			f"of {descriptor} Birth",
			f"of {descriptor} Blood",
			f"of {descriptor} Heritage",
			f"of {descriptor} Origin",
			f"of {descriptor} Birth",
			]

	if "Avens" in genus:
		origin += [
			"of the High Skies",
			"of the Soaring Winds",
			"of the Cloud Realm",

			"of the Endless Horizon",
			"of the Winged Tribes",
			]
		if "Owlin" in genus:
			origin += [
				"of the Moonlight",
				"of the Forests",
				"of Silence",
				"of the Skies",
				"of the Twilight",
				"of Wisdom",
				]
		if "Tengu" in genus:
			origin += [
				f"of the {descriptor} Tale",
				"of the Hidden Dojo",
				"of the Martial Paths",
				"of the Clever Beaks",
				]
		if "Raptoran" in genus:
			origin += [
				"of the Mountain Aeries",
				"of the Windcut Cliffs",
				"of the High Ridges",
				"of the Soaring Currents",
				"of the Lofty Nests",
				]
		if "Aarakocra" in genus:
			origin += [
				"of the Mountain Peak",
				"of the Spiraling Thermal",
				"of the Sacred Wind",
				"of the Cloud Monastery",
				"of the Heavenly Dances",
				]
		if "Kenku" in genus:
			origin += [
				"of the Echoing Voice",
				"of the Shadowed Alley",
				"of the Urban Jungle",
				"of the Crafty Beak",
				"of the Stolen Secret",
				]
		if "Birdfolk" in genus:
			origin += [
				"of the Verdant Forest",
				"of the Melodious Song",
				"of the Nested Height",
				"of the Diverse Plume",
				"of the Winged Assembly",
				]
	if "Aberration" in genus:
		origin += [
			"of Carcosa",
			"of the Deep",
			f"of the {descriptor} Deep",
			"of the Dark Void",
			f"of the {descriptor} Void",
			]

		if "Githzerai" in genus:
			origin += [
				"of the Inner Peace",
				"of the Mystic Paths",
				"of the Ascetic Way",
				"of the Spiritual Harmony",
				"of the Enlightened Realm",
				]
		if "Githyanki" in genus:
			origin += [
				"of the Astral Raids",
				"of the Conquered Realm",
				"of the Endless War",
				"of the Ruthless Campaign",
				"of the Dominant Force",
				]
		if "Destiny Devouers" in genus:
			origin += [
				"of Time",
				"of Destiny",

				"of the Vortex",
				]
		if "Parasyte" in genus:
			origin += [
				f"of the {descriptor} Bodies",
				f"of the {descriptor} Hive",
				f"of the {descriptor} Web",
				f"of the {descriptor} Realm",
				f"of the {descriptor} Infection",
				]
		if "Symbioid" in genus:
			origin += [
				f"of the {descriptor} Union",
				f"of the {descriptor} Hive",
				f"of the {descriptor} Web",
				f"of the {descriptor} Organism",
				]
		if "Alien Spawn" in genus:
			origin += [
				f"of the {descriptor} World",
				f"of the {descriptor} Realm",
				f"of the {descriptor} Cosmos",
				f"of the {descriptor} Dominions",
				f"of the {descriptor} Terror",
				]
		if "Chaos Warper" in genus:
			origin += [
				"of the Star Field",
				"of the Galactic Core",
				"of the Astral Plane",
				"of the Cosmic Void",
				"of the Nebula",
				]
		if "Living Spell" in genus:
			origin += [
				"of the Spell Storms",
				"of the Nexus",

				"of the Magical Anomalies",
				"of the Vortex",
				]
		if "Dominators" in genus:
			origin += [
				"of the Iron Will",
				"of the Dominant Chain",
				"of the Enslaved Realm",
				"of the Ruthless Order",
				"of the Commanding Heights",
				]
	if "Beast" in genus:
		origin += [
			"of the Pack",
			"of the Stampede",
			f"of the {descriptor} Stampede",
			"of the Jungle",
			f"of the {descriptor} Jungle",
			]
		if "Giant Eagle" in genus:
			origin += [
				"of the Soaring Height",
				"of the Mountain",
				"of the Sky",

				"of the Wind",
				"of the Cloud Kingdom",
				"of the Clouds",
				]
		if "Kong" in genus:
			origin += [
				f"of the {descriptor} Isle",
				f"of the {descriptor} Jungle",
				f"of the {descriptor} Grove",
				f"of the {descriptor} Peak",
				f"of the {descriptor} Wild",
				]
		if "Monkey King" in genus:
			origin += [
				f"of the {descriptor} Mischief",
				f"of the {descriptor} Path",
				f"of the {descriptor} Mountain",
				f"of the {descriptor} Realm",
				f"of the {descriptor} Adventure",
				]
		if "Armored Bear" in genus:
			origin += [
				f"of the {descriptor} Realm",
				f"of the {descriptor} Fortress",
				f"of the {descriptor} Clan",
				f"of the {descriptor} Woods",
				f"of the {descriptor} Defenders",
				]
		if "Tiger" in genus:
			origin += [
				"of the Snow",
				f"of the {descriptor} Mountain",
				f"of the {descriptor} Forests",
				f"of the {descriptor} Valleys",
				"of the Frost",
				"of the Hunt",
				f"of the {descriptor} Hunt",
				]
		if "Vulture" in genus:
			origin += [
				"of Death",
				f"of the {descriptor} Sky",
				f"of the {descriptor} Omen",
				f"of the {descriptor} Desert",
				]
		if "Deer" in genus:
			origin += [
				f"of the {descriptor} Woods",
				f"of the {descriptor} Glade",
				f"of the {descriptor} Trail",
				f"of the {descriptor} Path",
				f"of the {descriptor} Kingdom",
				f"of the {descriptor} Lake",
				]
		if "Owl" in genus:
			origin += [
				f"of the {descriptor} Knowledge",
				f"of the {descriptor} Sky",
				f"of the {descriptor} Hunt",
				f"of the {descriptor} Vision",
				f"of the {descriptor} Woods",
				]
	if "Kitsune" in genus:
		origin += [
			"of Nine Tails",
			"of Nine Tails",

			"of the Trickster",
			]
	if "Catfolk" in genus:
		origin += [
			"of the Pride",
			f"of the {descriptor} Pride",
			]
	if "Elf" in genus:
		origin += [
			"of Llanowar",
			"of the Elves",
			]
	if "Fiend" in genus:
		origin += [
			"of Heaven",
			"of Avernus",
			f"of the {descriptor} Heaven",
			"of Hades",
			"of the Underworld Gates",
			"of the Pit",
			]
	if "Undead" in genus:
		origin += [
			"of the Undead",
			"of the Living Dead",
			"of the Tomb",
			f"of the {descriptor} Tomb",
			"of the Bone",
			f"of the {descriptor} Bone",
			"of the Necropolis",
			f"of the {descriptor} Necropolis",
			"of the Tumulus",
			f"of the {descriptor} Tumulus",
			"of the Crypt",
			f"of the {descriptor} Crypt",
			"of the Catacombs",
			f"of the {descriptor} Catacombs",
			"of the Mausoleum",
			f"of the {descriptor} Mausoleum",
			"of the Crypt",
			f"of the {descriptor} Crypt",
			]
		if "Mummy" in genus:
			origin += [
				"of the Mummy",
				f"of the {descriptor} Mummy",
				"of the Sarchophagus",
				f"of the {descriptor} Sarchophagus",
				"of the Mummy's Curse",
				"of the Mummy's Wrath",
				"of the Mummy's Tomb",
				"of the Pyramid",
				f"of the {descriptor} Pyramid",
				"of the Zygurat",
				f"of the {descriptor} Zygurat",
				"of the Sphnx",
				f"of the {descriptor} Sphinx",
				"of the Tomb's King",
				"of the Tomb's Queen",
				f"of the Tomb's {rank}",
				"of the Damned",
				]

		if "Vampire" in genus:
			origin += [
				"of the Vampire",
				f"of the {descriptor} Vampire",
				]

	origin += [
		f"of the {descriptor} War",
		f"of the {rank} War",
		"of the Sun Stone",
		f"of the {descriptor} Stone",
		"of Souls",
		"of Bane",
		"of Tiamat",
		f"of The {descriptor} Town",
		"of the Forbidden Cave",
		"of the Frontier",
		"of the Gods",
		"of Fate",
		"of Freya",
		"of Icarus",
		"of Midgard",
		"of Prometheus",
		"of the Caribbean",
		"of the State",
		"of Monsters",
		f"of the {descriptor} Realm",
		f"of the {descriptor} Church",
		f"of the {descriptor} Dawn",
		f"of the {descriptor} Grove",
		f"of the {descriptor} Desert",
		f"of the {descriptor} Dragon",
		f"of the {descriptor} Elders",
		f"of the {descriptor} Faith",
		f"of the {descriptor} Forest",
		f"of the {descriptor} Kingdom",
		f"of the {descriptor} Mountain",
		f"of the {descriptor} Night",
		f"of the {descriptor} Phoenix",
		f"of the {descriptor} Plains",
		f"of the {descriptor} River",
		f"of the {descriptor} Sea",
		f"of the {descriptor} Star",
		f"of the {descriptor} Swamp",
		f"of the {descriptor} War",
		"of Vampires",
		f"of the {descriptor} Arts",
		f"of the {descriptor} Flame",
		f"of the {descriptor} Order",
		f"of the {descriptor} Eternal",
		f"of the {descriptor} Fire",
		f"of the {descriptor} Firestorm",
		f"of the {descriptor} Gate",
		f"of the {descriptor} Labyrinth",
		f"of the {descriptor} Mountain",
		f"of the {descriptor} Realm",
		f"of the {descriptor} Saga",
		f"of the {descriptor} Waterfall",
		f"of the {descriptor} Woods",
		f"of the {descriptor} Thieves",
		"of the Quest",
		"for Hire",
		"for Hire",
		"for Hire",
		"for Hire",
		"for Hire",
		"for Hire",
		"of Akroma",
		"of Athena",
		"of Baba Yaga",
		"of Death",
		"of Delphos",
		"of El Dorado",
		"of Eldorado",
		"of Elysium",
		"of Fate",
		"of Fire",
		"of Gold",
		"of Heaven",
		"of Hell",
		"of Hispaniola",
		"of Iron",
		"of Justice",
		"of La Noche Triste",
		"of Niflheim",
		"of Odin",
		"of Port Royal",
		"of Silver",
		"of Steel",
		"of the Abyss",
		"of the Seventh Hell",
		"of the Amulet",
		"of the Autumn",
		"of the Bamboo Grove",
		"of the City",
		"of the Crown",
		"of the Dead",
		"of the Desert",
		"of the Divine",
		"of the East",
		"of the East",
		"of the Endless Sands",
		"of the Eternal Saga",
		"of the Eternal",
		"of the Faith",
		"of the Fiend",
		"of the Forest",
		"of the Forest",
		"of the Forge",
		"of the Forty Thieves",
		"of the Galaxy",
		"of the Goblet",
		"of the Gods",
		"of the Golden City",
		"of the Griffon",
		"of the Hells",
		"of the Hidden",
		"of the Hill",
		"of the Hydra",
		"of the Jewel",
		"of the Jungle",
		"of the Kingdom",
		"of the Kraken",
		"of the Labyrinth",
		"of the Land",
		f"of the {descriptor} Land",
		"of the Last Fire",
		"of the Moon Wood",
		"of the Morningstar",
		"of the Mountain",
		"of the Mountain",
		"of the North",
		"of the North",
		"of the Oceans",
		"of the Odyssey",
		"of the Old One",
		"of the Oracle",
		"of the Pack",
		"of the People",
		"Of The Pharaoh",
		"Of The Plain",
		"of the Plains",
		"of the Ruby",
		"Of The Sands",
		"Of The Sea",
		"of the Sea",
		"of the Sky",
		"Of The South",
		"of the South",
		"Of The Spring",
		"Of The Storm",
		"Of The Summer",
		"of the Swamp",
		"of The Sword",
		"of The Talisman",
		"of the Thousand Tears",
		"of the Underworld Gate",
		"of the Underworld",
		"of the Waterfall",
		"Of The West",
		"of the West",
		"Of The Winter",
		"Of Thor",
		"of Uruk",
		"of Vasilisa",
		"of Whispers",
		"Of Youth",
		"Of Zeus",
		"of the Temple",
		"of the Dunes",
		f"of the {descriptor} Tomb",
		"of the Sun",
		"of the Golden Hoard",
		f"of the {descriptor} Hoard",
		]

	if "Rogue" in genus:
		origin += [
			"of the Shadows",
			f"of the {descriptor} Shadow",
			f"of the {descriptor} Plot",
			f"of the {descriptor} Escape",
			f"of the {descriptor} Underworld",
			f"of the {descriptor} Heist",
			]
	if "Shaman" in genus:
		origin += [
			f"of the {descriptor} Gods",
			f"of the {descriptor} Jungle",
			f"of the {descriptor} Rites",
			f"of the {descriptor} Visions",
			f"of the {descriptor} Forces",
			f"of the {descriptor} Traditions",
			f"of the {descriptor} Spirits",
			"of the Ancestral Spirits",
			]
	if "Spy" in genus:
		origin += [
			"of the Mission",
			"of the Undercover Operation",

			"of the Network",
			"of Reconnaissance",
			]
	if "Fiend" in genus:
		origin += [
			"of Avernus",
			]
	if "Traveler" in genus:
		origin += [
			f"of the {descriptor} Jungle",
			f"of the {descriptor} Path",
			f"of the {descriptor} Expedition",
			f"of the {descriptor} Tribe",
			f"of the {descriptor} Voyage",
			f"of the {descriptor} Discovery",
			]
	if "Trickster" in genus:
		origin += [
			"of the Street",
			f"of the {descriptor} Corner",
			f"of the {descriptor} Alleys",
			]
	if "Warrior" in genus:
		origin += [
			"of the Colosseum",
			f"of the {descriptor} Colosseum",
			f"of the {descriptor} Arena",
			f"of the {descriptor} Campaign",
			f"of the {descriptor} Conquest",
			f"of the {descriptor} Combat",
			f"of the {descriptor} Duels",
			f"of the {descriptor} War",
			]
	if "Warlock" in genus:
		origin += [
			f"of the {descriptor} Gods",
			"of the Deal",
			"of the King in Yellow",
			"of The Master",
			"of the Sold Soul",
			f"of the {descriptor} God",
			f"of the {descriptor} King",
			f"of the {descriptor} Lore",
			f"of The {descriptor} Master",
			f"of the {descriptor} Powers",
			f"of the {descriptor} Rites",
			f"of the {descriptor} Secrets",
			]
	if "Witch" in genus:
		origin += [
			"of La Llorona",
			"of the Enchanting Spell",
			f"of the {descriptor} Arts",
			f"of the {descriptor} Curse",
			f"of the {descriptor} Curses",
			f"of the {descriptor} Jungle",
			f"of the {descriptor} Ritual",
			f"of the {descriptor} Spell",
			f"of the {descriptor} Tradition",
			]
	if "Priest" in genus:
		origin += [
			"from Heaven",
			f"from the {descriptor} Heaven",
			f"of the {descriptor} Gods",
			"of the Orders",
			f"of the {descriptor} Congregation",
			f"of the {descriptor} Ministry",
			f"of the {descriptor} Order",
			f"of the {descriptor} Rite",
			f"of the {descriptor} Sanctuary",
			]
	if "Aberration" in genus:
		origin += [
			"of the Jungle",

			f"of the {descriptor} Jungle",
			]

	if "Shapeshifters" in genus:
		origin += [
			"of the Shifting Forms",
			"of the Many Faces",
			"of the Illusory Guises",

			"of the Changing Aspects",
			"of the Protean Nature",
			]
	if "Illithid" in genus:
		origin += [
			"of the Deep Mind",
			"of the Psychic Network",
			"of the Mind Harvest",

			"of the Brain Conclave",
			"of the Mental Dominion",
			]
	if "Beholder" in genus:
		origin += [
			"of the Thousand Eyes",
			"of the Unseen Terrors",
			"of the Realm",
			"of the Arcane",
			]
	if "Old One" in genus:
		origin += [
			"of the Ageless Eon",
			"of the Cosmic Depth",
			"of the Eldritch Secret",
			"of the Starry Void",
			"of the Ancient Mystery",
			]
	if "Mindlinker" in genus:
		origin += [
			"of the Collective Consciousness",
			"of the Wisdom Network",
			"of the Harmonious Minds",
			"of the Thought Weave",
			"of the Knowledge Nexus",
			]
	if "Noble" in genus:
		origin += [
			f"of the {descriptor} Palace",
			f"of the {descriptor} Court",
			f"of the {descriptor} Estate",
			f"of the {descriptor} Mansions",
			f"of the {descriptor} Council",
			f"of the {descriptor} Assembly",
			]
	if "Goblin" in genus:
		origin += [
			"of the Clan Zanzigzags", "of the Clan Fuddleheads", "of the Caravan of Nowherelse",
			"of the Pirate Paraders", f"of the {descriptor} Klan", "of the Rusty Dagga Klan", f"of the {descriptor} Dagga Klan", "of the Broke Toof Klan",
			f"of the {descriptor} Toof Klan", "of the Sneeky Shaddaz Klan", f"of the {descriptor} Shaddaz Klan", "of the Raginfaya Klan", f"of the {descriptor} Fiya Klan",
			"of the Laffinskullz Klan",
			f"of the {descriptor} Skull Klan", f"of the {descriptor} Moon Klan", "of the Mystik Mushrumz Klan",
			"of the Spareem Klan", "of the Gligrove Klan", "of the Frosternz Klan", "of the Vybroilet Klan", "of the Whimzikren Klan", "of the Moonlinyun Klan", "of the Dazzliancaz Klan", "of the Enchantenvoyz Klan", "of the Silvant Klan", "of the Gleamguard Klan", "of the Raydirunnaz Klan", "of the Mystinger Klan", "of the Faefollowaz Klan", "of the Shaddasneek Klan", "of the Lunalurka Klan", "of the Sinistez Klan", "of the Vortekandalz Klan", "of the Zanizip Klan", "of the Puzzleress Klan", "of the Trickytinka Klan", "of the Unbrites Klan", "of the Snareroot Clan", "of the Gravetooth Gigglers", "of the Marblesharp Klan", "of the Shaddafriend Klan", "of the Tanglestride Clan", "of the Wackiskaz Klan",
			"of the Riddleskull Clan", "of the Gigglang Klan", "of the Twistailz Klan", "of the Crookknee Clan", "of the Zanzigzagz Klan", "of the Quirkilz Klan", f"of the {descriptor} Pirates", f"of the {descriptor} Horde", f"of the {descriptor} Nomadz", f"of the {descriptor} Swampz Klan", f"of the {descriptor} Leafz Klan", f"of the {descriptor} Shade Klan", "of the Sinistart Klan", "of the Ravvinlot Klan",
			"of the Riddleburr Clan", "of the Springsprong Klan", "of the Sneekyshadda Klan", "of the Lonesok Klan", "of the Sparkypark Klan", "of the Spisnow Conez Klan", "of the Skwiril Klan", "of the Stalkawalkaz Klan", "of the Threshold Shades", "of the Suntare Lot", "of the Swifity Klan", "of the Silvarviz Klan", "of the Silvandaz Klan", "of the Talktrees Lot", "of the Whizirlaz Klan", "of the Wilboarz Lot", "of the Witbitz Klan", "of the Woozlez Klan", "of the Wandrerz Klan", "of the Wrongwayz Klan", "of the Zany Zip-Zip Klan", f"of the {descriptor} Dagga", f"of the {descriptor} Fiya", f"of the {descriptor} Moon", f"of the {descriptor} Serpent", f"of the {descriptor} Shadda", f"of the {descriptor} Skull", f"of the {descriptor} Toof", f"of the {descriptor} Tree",
			f"of the {descriptor} Wolf", "of the Redhats Klan", "of the Traphunters Clan", f"of the {descriptor} Clan", "of the Rustydagger Clan", f"of the {descriptor} Dagger Clan",
			"of the Brokentooth Clan", f"of the {descriptor} Tooth Clan", "of the Sneaky Shadows Clan",
			f"of the {descriptor} Shadow Clan", "of the Ragingfire Clan", f"of the {descriptor} Fire Clan", "of the Cunninfox Clan", "of the Wildboar Clan", "of the Quickfoot Clan", "of the Slyraven Clan", "of the Mudwater Clan", "of the Gleamgem Clan", "of the Fierce Wolf Clan", f"of the {descriptor} Wolf Clan", "of the Bounrabbit Clan",
			"of the Laughskull Clan", f"of the {descriptor} Skull Clan", "of the Dancileaf Clan", "of the Twilickster Clan", "of the Lunantern Clan", f"of the {descriptor} Moon Clan", "of the Mystimushroom Clan", "of the Whisperwillow Clan", "of the Starstalker Clan", "of the Enchantember Clan", "of the Dancedrop Clan", "of the Shimmershade Clan", "of the Gleaminglade Clan", "of the Blinkblossom Clan", "of the Sparkleam Clan", "of the Glimmerove Clan",
			"of the Sylvadow Clan", "of the Charmerry Clan", "of the Moonmarauder Clan", "of the Deweamer Clan", "of the Frostern Clan", f"of the {descriptor} Tree Clan", "of the Etherelm Clan", "of the Vibriolet Clan", "of the Whimsicren Clan", "of the Moonlinion Clan", "of the Dazzlancer Clan", "of the Enchantenvoy Clan", "of the Sylvant Clan", "of the Gleamguardian Clan", "of the Radiant Runner Clan", "of the Mystic Messenger Clan", "of the Whimward Clan", "of the Fey Messenger Clan", "of the Nocturnal Nuisance Clan", "of the Mystic Mirage Clan", "of the Twilight Trickster Clan", "of the Dusk Dweller Clan", "of the Midnight Marauder Clan", "of the Veiled Vagabond Clan", "of the Lunar Lurker Clan", "of the Nightshade Clan", "of the Crimson Clan", "of the Vortex Vandals", "of the Moxier Clan", "of the Unbrights Clan", "of the Laterunner Clan", "of the Shadowtrippers Clan", "of the Moonlit Misrule Clan", "of the Jarstuckers Clan", "of the Dancing Tree Clan", "of the Rockmunch Clan", "of the Sunstarer Clan", "of the Tallyrot Clan", "of the Moonbark Clan", "of the Marblesharp Clan", "of the Redsnow Clan", "of the Shadowfriend Clan", "of the Broken Compass Nomads", "of the Tail Twisters Clan", f"of the {descriptor} Pirates", f"of the {descriptor} Horde", f"of the {descriptor} Nomads", f"of the {descriptor} Travelers", f"of the {descriptor} Swamp", f"of the {descriptor} Leaf", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan",
			f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan",
			f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan",
			f"of the {descriptor} Clan", f"of the {descriptor} Clan", f"of the {descriptor} Clan",
			f"of the {descriptor} Clan",
			f"of the {descriptor} Clan",
			f"of the {descriptor} Clan",
			f"of the {descriptor} Clan",
			"of the Boggle Clan",
			"of Brilliantbolt Clan",
			"of the Broken Compass Nomads",
			"of Brokentooth Clan",
			"of the Trickster Clan",
			"of the Dull Blade Clan",
			"of the Dusk Dwellers",
			"of the Enchanember Clan",
			"of the Pumpkin Smasher Clan",
			"Of the Dreamwalker Clan",
			"of the Enchanted Elm Clan",
			"of the Treethrower Clan",
			"of the Tripfeet Clan",
			"of the Holefeller Clan",
			"of the Feywild Fellows",
			"of the Fierce Wolf Klan",
			"of the Forgotten Name Clan", "of the Fuzzy Clan", "of the Gleamgem Clan",
			"of the Gleamglade Clan", "of the Gringuardian Clan", "of the Gloomgrin",
			"Of the Bulcander Clan", "of the Lost Clan", "of the Hidden Clan",
			"of the Laughing Skull Clan", "of the Lost Clan", "of the Lost Marble Clan",
			"of the Lunar Lurker Clan", "of the Lustrous Clan", "of the Marblesharp Klan", "of the Tatiana Messengers Clan", "of the Oberon Messengers Clan", "of the Midnight Marauder Klan", "of the Moonbark Klan", f"of the {descriptor} Mystic Clan", f"of the {descriptor} Mushroom Clan", "of the Nightshade Clan", f"of the Nocturnal {rank}", f"of the {descriptor} Brawler", "of the Keenscent Clan", "of the Unbright Clan", "of the Obsidian Clan", "of the Quickfoot Clan", "of the Radiant Runner Clan", "of the Redhats", "of the Redsnow Klan", "of the Rock Eater Clan", "of the Rusty Clan", "of the Shadow Clans", f"of the {descriptor} Shade", f"of the {descriptor} Raven", "of the Spring Court", "of the Sunstarer Clan", "of the Titan's Servant Clan", "of the Sylvan Shadows", "of the Traphunter Clan", "of the Veiled Vagabonds", "of the Vortex Vandals", "of the Whispering Willow Clan", "of the Wild Boar Clan", "of the Wrong Nomads", f"of the {descriptor} Clan", f"of the {descriptor} Dagger Clan", f"of the {descriptor} Fire Clan", f"of the {descriptor} Moon Clan", f"of the {descriptor} Serpent Clan", f"of the {rank} Shadow Clan", f"of the {descriptor} Shadow Clan", f"of the {descriptor} Skull Klan", f"of the {descriptor} Tooth Clan", f"of the {descriptor} Tree Clan", f"of the {descriptor} Wolf Clan", "of the Redhat Clan",
			"of the Trapsnack Hunters Clan",
			"of the Bright Shadow Clan",
			"of the Harmless Marauders",
			"of the Foxfire Clan",
			"of the Tealeaf Tricksters",
			"of the Dewdrop Dancer Clan", "of the Peacebrawlers", "of the Startrail Stalkers", "of the Briarhop Clan", "of the Hollowstep Marchers", "of the Wallwalkers", "of the Sock Seekers", "of the Witchlight Wastrels", "of the Beerspearer Clan", "of the Dagger Swagger Clan", "of the Moon Goons", "of the Shade Parade",
			"of the Fireflyers", "of the Veilvanish", "of the Midmuckers", "of the Gloomgrin Gang",
			"of the Mystic Messengers", "of the Mud Nomads", "of the Leaf Loafers", "of the Swamp Marchers", f"of the {descriptor} Horde", f"of the {rank} Horde", "of the Pirate Parade", f"of the {rank} Parade", f"of the {descriptor} Firedancers", f"of the {descriptor} Wolfriders", f"of the {descriptor} Pirates",
			f"of the {descriptor} Horde", f"of the {descriptor} Nomads", f"of the {descriptor} Travelers", f"of the {descriptor} Leaflurkers", "of the Bramblebunch Clan", "of the Clan Rubaruse", "of the Clan Sarisandal", "of the Clan Rumrazor", "of the Klan Makrobaz", "of the Clan Bargabeh", "of the Klan Willowhisper", "of the Star Stalker Clan", "of the Shadeshimmer Clan",
			"of the Gladegleamer Clan", "of the Clan Baglimmer", "of the Clan Zilsylvan", "of the Klan Anarkarmers", "of the Clan Derakrifters", "of the Clan Barqaruners",
			"of the Lamalacky Klan", "of the Veiled Vagabonds", "of the Gloomgrin Gang", "of the Toolate Caravan", "of the Briar Mask Tricksters", "of the Wrong Dune Caravan", "of the Clan Jarstuckjam", "of the Clan Headbonkers", "of the Pathless Caravan", "of the Slipshadow Caravan", "of the Wallwalkers Clan", "of the Sunstare Society", "of the Clan Treetalkers", "of the Clan Moonbarkers", f"of the {descriptor} Nomads",
			f"of the {descriptor} Clan",
			"of the Dullblade Nomads", "of the Kabila Mudmind Mystics", f"of the {descriptor} Caravan", "of the Broken Compass Caravan", f"of the {descriptor} Troupe", "of the Turvy Troupe", "of the Fluzzy Clan", "of the Clan Wacky Whiskers", "of the Clan Tailtwisters", "of the Zigzagers", "of the Clan Quirkyquills", "of the Fuddleheads", "of the Green Horde", "of the Caravan of Nowherelse", "of the Dustway Nomads",
			"of the Leaflurker Travelers", "of the Swamp Stompers", "of the Parade Pirates",
			f"of the {descriptor} Wolf Whistlers", f"of the {descriptor} Skull Clan",
			f"of the {descriptor} Moon {rank} Clan", f"of the {descriptor} Fire Dancers Clan",
			"of the Redjatz Klan",
			"of the Trapunters Klan",
			f"of the {descriptor} Firedancers Clan", "of the Clan Rubahruse",
			"of the Clan Dandanxekan", "of the Kabila Zillers", "of the Clan Gurazgallop",
			"of the Forgoten Name Clan",
			]
	if "Undead" in genus:
		origin += [
			"of the Ossuary",
			"from the Ossuary",
			f"of the {descriptor} Ossuary",
			"of the Mummy",
			f"of the {descriptor} Mummy",
			"of the Zombies",
			]

	if "Evil" in genus:
		origin += [
			"of Cruelty",
			]

	origin += [
		"of Cyclops",
		"of the Cyclops",
		"of Agonas",
		"of the Moon",
		"of the Moonlit Glades",
		"of the Mystical Moons",
		"of Mythic Battles",
		"of the Natural Springs",
		"of the Night",
		"of the Obscured Mysteries",
		"of the Otherworldly Visions",
		"of the Powerful Empires",
		"of the Raven Queen",
		"of the Woodlands",
		"of Air",
		"of Dragons",
		f"of the {descriptor} Dragon",
		"of Earth",
		f"of the {descriptor} Earth",
		f"of the {descriptor} Heaven",
		"of Hell",
		f"of the {descriptor} Hell",
		f"of the {rank} Hell",
		"of Life",
		"of Light",
		f"of the {descriptor} Light",
		"of Nature",
		"of the Primal Essence",
		f"of the {descriptor} Essence",
		"of the Abbey",
		f"of the {descriptor} Abbey",
		"of the Abyss",
		"of the Abyssal Depths",
		"of the Academy",
		f"of the {descriptor} Academy",
		"of Ageless Wisdom",
		f"of {descriptor} Wisdom",
		"of the Ages",
		"of the Ancient Tribe",
		f"of the {descriptor} Tribe",
		"of the Beast Realm",
		f"of the {rank} Realm",
		"of the Blackened Sky",
		f"of the {descriptor} Sky",
		"of the Blessed Waters",
		"of the Divine",
		"of Divine Will",
		"of Zeus' Will",
		"of Odin's Will",
		"of Thor's Will",
		"of Gods' Will",
		"of God's Will",
		"of King's Will",
		f"of {rank}'s Will",
		"of the Dread Fortress",
		f"of the {descriptor} Fortress",
		"of the Elements",
		"of the Endless Night",
		f"of the {descriptor} Night",
		"of the Santa Campaña",
		"of the Eternal Chains",
		f"of the {descriptor} Chains",
		"of the Eternal Clock",
		"of the Eternal Watch",
		f"of the {descriptor} Watch",
		"of the Eternal Flame",
		f"of the {descriptor} Flame",
		"of the Ethereal Realm",
		f"of the {descriptor} Realm",
		"of the Fiery Lake",
		f"of the {descriptor} Lake",
		"of the Forbidden Arts",
		f"of the {descriptor} Arts",
		"of the Forbidden Knowledge",
		f"of the {descriptor} Knowledge",
		"of the Forbidden Throne",
		f"of the {descriptor} Throne",
		"of the Forces",
		f"of the {descriptor} Forces",
		"of the Fungal Forests",
		"of the Gale",
		"of the Glaciers",
		"of the Glade",
		"of Hellfire",
		f"of the {descriptor} Void",
		"of the Infernal Realm",
		f"of the {descriptor} Realm",
		"of the Inferno",
		f"of the {descriptor} Inferno",
		"of Lava",
		"of the Light",
		f"of the {descriptor} Light",
		"of Light",
		"of the Lost Library",
		f"of the {descriptor} Library",
		"of the Mythic Tale",
		f"of the {descriptor} Tale",
		"of Nature's Heart",
		"of Nature",
		"of the Netherworld",
		"of the Ninth Circle",
		"of Past and Future",
		"of the Primal Forest",
		f"of the {descriptor} Forest",
		"of the Realm",
		"of the Reptilian Marshes",
		"of the Road",
		f"of the {descriptor} Road",
		"of the Rocks",
		f"of the {descriptor} Rock",
		"of the Ruined Empire",
		"of the Old Empire",
		"of the Empire",
		"of the Gone Empire",
		"of the Rising Empire",
		f"of the {descriptor} Empire",
		"of the Searing Flame",
		"of the Shadowflame",
		"of the Shadows",
		f"of the {descriptor} Shadows",
		"of The Shapeless",
		"of the Slime Pits",
		"of the Spheres",
		"of the Sphere",
		f"of the {descriptor} Sphere",
		"of the Tempest",
		"of The Tempest",
		f"of The {descriptor} Tempest",
		"of the Timeless Realm",
		f"of the {descriptor} Realm",
		"of The Tormented",
		"of the Unseen Terror",
		"of the Unseen",
		"of the Untamed Wilds",
		"of the Wailing Abyss",
		"of the Wild",
		"of the Woods",
		"of Water",
		f"of the {descriptor} Realm",
		f"of the {descriptor} Gods",
		f"of the {descriptor} Forest",
		"of the Enchanted Woods",
		"of the Eternal King",
		"of the Eternal Queen",
		"of the Eternal Regent",

		"of the Edge",
		"of the Blade",
		]

	result = lusor.Pick(
		origin,
		dice=dice,
		)
	return result
